### ISSUE TITLE
exit_status test fails on a lot of environment

### ISSUE THREAD

**Issue by punytan** [gugod/App-perlbrew#121]
According to http://www.cpantesters.org/distro/A/App-perlbrew.html#App-perlbrew-0.25 , most of all cpantesters environment fails and produces the result that `Failed test at t/09.exit_status.t line 27`.

The test is:

     `perlbrew version 2>&1`;
     ok($? == 0);

If testing environment doesn't have perlbrew, the executed statement sets `$?` as non-zero value.

I'm considering two point to prevent such a problem.
- add test to detect the perlbrew is installed or not 
- skip following tests if the environment doesn't have perlbrew itself

Any thoughts?

**Comment by gugod** [comment]
test matrix looks green (mosly): http://www.cpantesters.org/distro/A/App-perlbrew.html

we probably don't need more effort on this issue.

Cheers.
