### ISSUE TITLE
Image::Magick fails to link against libperl.a

### ISSUE THREAD

**Issue by rwstauner** [gugod/App-perlbrew#131]
I'm failing to install Image::Magick (PerlMagick) into my brewed perl-5.14.1

I'm trying to figure out the root problem/solution,
but it appears I'm not the first to run into this:

http://www.webmasterkb.com/Uwe/Forum.aspx/perl-module/1017/Problems-with-cpan#4D98C5273050405gmailcom
http://www.mail-archive.com/london.pm@london.pm.org/msg20830.html

I'm not sure if perhaps when brewed perl should have -L$prefix/lib/5.14.1/x86_64-linux/CORE added to Config{ldflags} or something like that...

I'm still trying to find the right arguments to get PerlMagick installed
but I wanted to document the issue here.

**Comment by gugod** [comment]
I'm not sure if this is still actionable within the scope of perlbrew project, so I'm closing this issue for now. Thanks all.
