### ISSUE TITLE
perlbrew: command not found (custom PERLBREW_ROOT)

### ISSUE THREAD

**Issue by davewood** [gugod/App-perlbrew#193]
fresh debian squeezy

I am trying to install a custom perl in /opt as user root

1) export PERLBREW_ROOT=/opt/perlbrew
2) wget --no-check-certificate -O - http://install.perlbrew.pl | bash
3) add "source /opt/perlbrew/etc/bashrc" to ~/.bash_profile
4) logout
5) login again
6) perlbrew appears in tab completion but if i execute it ... "-su: perlbrew: command not found"

Notes:
1) if I skip steps 5 and 5 and source the perlbrew-bashrc manually perlbrew can be executed. But if I logout only once the same problem appears
2) if I omit PERLBREW_ROOT prelbrew executes just fine.

**Comment by srchulo** [comment]
So this fixed it for you? I have this in my .bashrc:

export PERLBREW_ROOT=/opt/perlbrew
source /opt/perlbrew/etc/bashrc

And I'm still getting "-bash: perlbrew: command not found"
