### ISSUE TITLE
format_perl_version causes warning with 5.8.0

### ISSUE THREAD

**Issue by jtbraun** [gugod/App-perlbrew#194]
If you install perl-5.8.0, most perlbrew commands complain about a non-numeric argument:
> perlbrew list
Argument "" isn't numeric in sprintf at /loader/0x86d4f74/App/perlbrew.pm line 186.
* perl-5.8.0

I believe that format_perl_version should include "|| 0" for the second and third substr() calls, as shown below:

sub format_perl_version {
    my $self = shift;
    my $version = shift;
    return sprintf "%d.%d.%d",
      substr( $version, 0, 1 ),
      substr( $version, 2, 3 ) || 0,
      substr( $version, 5 ) || 0;

}

**Comment by gugod** [comment]
This does not happen on 0.74 anymore. So I'm closing this issue.
