### ISSUE TITLE
Solution: Install perlbrew with Ubuntu or Debian

### ISSUE THREAD

**Issue by lucas1** [gugod/App-perlbrew#202]
system 32bit:
$ perlbrew install perl-5.14.2 -Dusethreads -Duselargefiles -Dcccdlflags=-fPIC -Dpager=/usr/bin/sensible-pager -Doptimize=-O2 -Duseshrplib -Darchname=i386-linux-gnu -Dccflags=-DDEBIAN -Dplibpth=/usr/lib/i386-linux-gnu

system 64bit:
$ perlbrew install perl-5.14.2 -Dusethreads -Duselargefiles -Dcccdlflags=-fPIC -Dpager=/usr/bin/sensible-pager -Doptimize=-O2 -Duseshrplib -Duse64bitall -Darchname=x86_64-linux-gnu -Dccflags=-DDEBIAN -Dplibpth=/usr/lib/x86_64-linux-gnu

Solution by: http://bitsnoarame.blogspot.com.br/2012/03/perlbrew-em-ubuntu-1110.html

**Comment by mperry2** [comment]
Is this issue still valid? I've installed Perl using Perlbrew on Debian without having to use this method.

**Comment by gugod** [comment]
Thanks to @mperry2 -- I'm not sure what to follow-up on this issue either. So it is closed.
