### ISSUE TITLE
hardcoded URL http://search.cpan.org/CPAN/authors/id/

### ISSUE THREAD

**Issue by andk** [gugod/App-perlbrew#208]
https://metacpan.org/source/GUGOD/App-perlbrew-0.42/lib/App/perlbrew.pm#L620

Hardcoded URLs in programs make me always nervous. There is the case that I have a local mirror, that the URL goes away, that I disturb the owner of the URL, etc., etc.

Can we have a perlbrew that lets me choose from where the download happens?

Thanks!

**Comment by gugod** [comment]
There are still some search.cpan.org URLs in the code, but now we can set this env var:
 
    PERLBREW_CPAN_MIRROR

To a "http://" cpan mirror URL to allow downloading perl tarballs from different mirrors. I'm closing this issue now... let me know if more actions are needed.
