### ISSUE TITLE
Requires cpanminus

### ISSUE THREAD

**Issue by lsr** [gugod/App-perlbrew#214]
I tried installing perlbrew on a new vpn running CentOS 5.6 and had trouble.

Perlbrew installed fine with curl -kL http://install.perlbrew.pl | bash

Coming to installing an available perl I received the error that I should try installing the newest version of patchperl (already newest version) and try installing with --force (which would display the same error).

build.log would output 
Auto-guessed '5.101'
No patch utility found
patching lib/Archive/Tar/t/02_methods.t/

And no further errors or information would show. 

Then I guessed I should install cpanminus and everything worked smoothly. 

Would it be worth mentioning somewhere that cpanminus should be installed before you can install a perl, or prompt the user to install cpanminus if it is not available? This may be a CentOS specific problem, I did not test on other distributions.

**Comment by sboehringer** [comment]
You need to install the command line tool ```patch```
