### ISSUE TITLE
Proposed version cannot be installed

### ISSUE THREAD

**Issue by mvuets** [gugod/App-perlbrew#219]
This snippet should be self-explanatory:

```
~$ perlbrew available
i perl-5.17.1
i perl-5.16.0
i perl-5.14.2
i perl-5.12.4
i perl-5.10.1
i perl-5.8.9
i perl-5.6.2
  perl5.005_04
  perl5.004_05
  perl5.003_07
~$ perlbrew install perl5.003_07
Unknown installation target "perl5.003_07", abort.
Please see `perlbrew help` for the instruction on using the install command.
```

**Comment by erickpaquin** [comment]
Hi @mvuets , can this issue be closed? It's over 10 years old, don't think it's relevant anymore. Thanks.

**Comment by mvuets** [comment]
@erickpaquin *shrug* Can't check now, nor in the near future-- I leave the decision up to you.

**Comment by erickpaquin** [comment]
@mvuets . I do not believe I have the permission to close this issue. Can you close it please? Thanks.

**Comment by mvuets** [comment]
Closed as per @erickpaquin's request.
