### ISSUE TITLE
requesting to use / switch-to a bogus lib does not report failure

### ISSUE THREAD

**Issue by rjbs** [gugod/App-perlbrew#224]
If I ask to use a perl that does not exist, I get an error:

    ~$ perlbrew use 1.2.3
    
    ERROR: The installation "1.2.3" is unknown.
    
    ~$ echo $?
    1

If I ask to use a perl that **does** exist with a *lib* that doesn't, it acts like it worked:

    ~$ perlbrew use 17.2@does-not-exist
    ~$ echo $?
    0

This bug also exists with "switch."

**Comment by gugod** [comment]
(I'm just reviewing and closing some aged issues....)

This now produce an error like:

    > perlbrew use 1.2.3
    
    ERROR: The installation "1.2.3" is unknown.
