### ISSUE TITLE
--quiet option does not work with exec

### ISSUE THREAD

**Issue by bricas** [gugod/App-perlbrew#242]
It doesn't seem to matter where I place the option, it doesn't work as expected:

$ perlbrew --quiet exec "perl -v"
Can't exec "exec": No such file or directory at /loader/0x1bfef4d8/App/perlbrew.pm line 31.

$ perlbrew exec --quiet "perl -v"
Can't exec "--quiet": No such file or directory at /loader/0x1350a4d8/App/perlbrew.pm line 31.

**Comment by gugod** [comment]
Close this issue because it's fixed :+1:
