### ISSUE TITLE
If PERLBREW_ROOT is set to ~/.perl5 before install, PATH is clobbered

### ISSUE THREAD

**Issue by krismatthews** [gugod/App-perlbrew#273]
If you install Perlbrew via

export PERLBREW_ROOT=~/.perl5
curl -kL http://install.perlbrew.pl | bash

Then add 

source ~/.perl5/etc/bashrc

Log out, and back in. PATH now contains only ~/bin:~/.perl5/bin

If you repeat the process but do not specify PERLBREW_ROOT, everything works fine.

/etc/redhat_release is "CentOS release 6.3 (Final)".

Thanks!

**Comment by zbentley** [comment]
I believe that this is resolved and can be closed. If I try to install perlbrew to a nonstandard location, I get e.g.
```
## Installing perlbrew
mkdir /foo: Permission denied at perlbrew.w3357j line 121.
```

While running `curl | bash`. Adding `source` commands to my shell for a nonexistent file in that directory does not corrupt the contents of my `$PATH` variable.

I am also unable to reproduce the issue when using a manually set `PERLBREW_ROOT=~/.perl5`, writable or not.

**Comment by krismatthews** [comment]
This does appear to be fixed. :+1:
