### ISSUE TITLE
Installation of perl-5.14.2 hangs

### ISSUE THREAD

**Issue by maikroeder** [gugod/App-perlbrew#282]
Hi,

When I install Perl 5.14.2

 perlbrew install perl-5.14.2

It hangs at this position:

vagrant@lucid64:~$ tail -f ~/perl5/perlbrew/build.perl-5.14.2.log
../ext/re/t/reflags.t ............................................. ok
../ext/re/t/regop.t ............................................... ok
../lib/AnyDBM_File.t .............................................. ok

Any hints how to solve this would be welcome.

Cheers,

Maik

**Comment by gugod** [comment]
I'm closing this issue as since it does not have much to do with perlbrew itself. Feel free to re-open if that's not the case.
