### ISSUE TITLE
Problem with perlbrew install-cpanm

### ISSUE THREAD

**Issue by maikroeder** [gugod/App-perlbrew#283]
Hi,

What can I do to trace the

perlbrew install-cpanm

ERROR: Failed to retrieve cpanm executable.

When running

I get the following when running "strace perlbrew install-cpanm"

fstat(4, {st_mode=S_IFREG|0644, st_size=22952, ...}) = 0
mmap(NULL, 2118160, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f66c87de000
mprotect(0x7f66c87e3000, 2093056, PROT_NONE) = 0
mmap(0x7f66c89e2000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x4000) = 0x7f66c89e2000
close(4)                                = 0
mprotect(0x7f66c89e2000, 4096, PROT_READ) = 0
brk(0x1887000)                          = 0x1887000
brk(0x18a8000)                          = 0x18a8000
brk(0x18c9000)                          = 0x18c9000
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
stat("/home/vagrant/perl5/perlbrew/bin/cpanm", 0x1345130) = -1 ENOENT (No such file or directory)

Cheers,

Maik

**Comment by yufeng1990** [comment]
Thanks @AHinMaine .It is also useful @msouth
