### ISSUE TITLE
Support perlbrew on win32 (strawberry)

### ISSUE THREAD

**Issue by azawawi** [gugod/App-perlbrew#31]
Strawberry Perl has gcc built-in. I noticed that perlbrew fails to even 'perlbrew init'. It would be cool that i can have perlbrew on win32? 

P.S. you need to use $ENV{USERPROFILE} instead of $ENV{HOME} and maybe use File::HomeDir?

Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at C:/str
awberry/perl/site/lib/App/perlbrew.pm line 11.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at C:/str
awberry/perl/site/lib/App/perlbrew.pm line 124.
Use of uninitialized value $ENV{"SHELL"} in pattern match (m//) at C:/strawberry
/perl/site/lib/App/perlbrew.pm line 195.
Use of uninitialized value in concatenation (.) or string at C:/strawberry/perl/
site/lib/App/perlbrew.pm line 204.
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at C:/str
awberry/perl/site/lib/App/perlbrew.pm line 11.
Use of uninitialized value $ENV{"SHELL"} in pattern match (m//) at C:/strawberry
/perl/site/lib/App/perlbrew.pm line 566.
Perlbrew environment initiated, required directories are created under

**Comment by gugod** [comment]
There's now berrbrew project that covers such needs on Windows: https://github.com/stevieb9/berrybrew
