### ISSUE TITLE
[solved]switch is not permanent on OSX 10.8.3

### ISSUE THREAD

**Issue by toratora** [gugod/App-perlbrew#312]
# Solved.

I failed to check .bash_profile which looked like this:

```
Toras-MacBook-Pro:~ toratora$ cat .bash_profile
# Added by install_latest_perl_osx.pl
[ -r /Users/toratora/.bashrc ] && source /Users/toratora/.bashrc

##
## Your previous /Users/toratora/.bash_profile file was backed up as /Users/toratora/.bash_profile.macports-saved_2013-04-05_at_17:30:24
##

## MacPorts Installer addition on 2013-04-05_at_17:30:24: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
## Finished adapting your PATH environment variable for use with MacPorts.
```

The final export PATH was clobering the PATH after perlbrew set it.  I moved the first two lines to the bottom, now it's fine across terminal sessions.
# Original:

For some reason the switch command doesn't switch the perl version permanantly, meaning when I open a new terminal window, I'm back to the system version.

Here's what I start out with in a new terminal window:
    Toras-MacBook-Pro:~ toratora$ perl -v

```
This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level

Toras-MacBook-Pro:~ toratora$ which perl
/opt/local/bin/perl
Toras-MacBook-Pro:~ toratora$ which perlbrew
/Users/toratora/perl5/perlbrew/bin/perlbrew
Toras-MacBook-Pro:~ toratora$ echo $PATH
/opt/local/bin:/opt/local/sbin:/Users/toratora/perl5/perlbrew/bin:/Users/toratora/perl5/perlbrew/perls/perl-5.16.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
```

Then I do the switch and I get:
    Toras-MacBook-Pro:~ toratora$ perlbrew switch perl-5.16.0
    Toras-MacBook-Pro:~ toratora$ perl -v

```
This is perl 5, version 16, subversion 0 (v5.16.0) built for darwin-2level

Toras-MacBook-Pro:~ toratora$ which perl
/Users/toratora/perl5/perlbrew/perls/perl-5.16.0/bin/perl
Toras-MacBook-Pro:~ toratora$ which perlbrew
/Users/toratora/perl5/perlbrew/bin/perlbrew
Toras-MacBook-Pro:~ toratora$ echo $PATH
/Users/toratora/perl5/perlbrew/bin:/Users/toratora/perl5/perlbrew/perls/perl-5.16.0/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
```

Excellent, all is working well.  But I open a new terminal session and I'm back to:
    Last login: Wed Apr 17 10:31:18 on ttys003
    Toras-MacBook-Pro:~ toratora$ perl -v

```
This is perl 5, version 12, subversion 4 (v5.12.4) built for darwin-thread-multi-2level

Toras-MacBook-Pro:~ toratora$ which perl
/opt/local/bin/perl
Toras-MacBook-Pro:~ toratora$ which perlbrew
/Users/toratora/perl5/perlbrew/bin/perlbrew
Toras-MacBook-Pro:~ toratora$ echo $PATH
/opt/local/bin:/opt/local/sbin:/Users/toratora/perl5/perlbrew/bin:/Users/toratora/perl5/perlbrew/perls/perl-5.16.0/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
```

and I still get this in the new session:
    Toras-MacBook-Pro:~ toratora$ perlbrew switch
    Currently switched to perl-5.16.0

Looks like a problem with the new $PATH not being saved but I'm not sure what to do about it.

**Comment by MaxBec** [comment]
hey guys,

for me it isn't fixing the problem. On every restart of the terminal (zsh) perl is back to /usr/bin/perl

This is the last line in my .zshenv:
```
# Source the perlbrew bash file
source ~/perl5/perlbrew/etc/bashrc
```

**Comment by gugod** [comment]
@MaxBec do you mind providing a bit more info on this matter in a new Issue ? I'm not sure re-opening a 7-year issue and mixing-in whatever outdated context in here would be a helpful idea... :)

Info such as the following would be helpful for troubleshooting:

- the content of `$PATH` in a fresh terminal
- the output of `perlbrew info` in a fresh terminal

Additionally, perhaps:

- mac os version
- zsh version
