### ISSUE TITLE
list-modules doesn't work with alias

### ISSUE THREAD

**Issue by gmorten1** [gugod/App-perlbrew#336]
```
> perlbrew --version
/opt/perl5/bin/perlbrew  - App::perlbrew/0.63
> perlbrew list
* perl-5.14.2
  perl-5.16.3
> perlbrew list-modules
[ returns long list ]
> perlbrew alias create perl-5.14.2 alias1
> perlbrew use alias1
> perlbrew list
* alias1 (5.14.2)
  perl-5.14.2
  perl-5.16.3
> perlbrew list-modules
> 
[returns nothing]
```

**Comment by y** [comment]
This appears to work:

    diff --git a/lib/App/perlbrew.pm b/lib/App/perlbrew.pm
    index 128ae0f..0aafdc5 100644
    --- a/lib/App/perlbrew.pm
    +++ b/lib/App/perlbrew.pm
    @@ -2285,9 +2285,16 @@ sub run_command_upgrade_perl {
    sub run_command_list_modules {
        my ($self) = @_;
        my $class = ref($self) || __PACKAGE__;
    +
    +    my $name = $self->current_env;
    +    if (-l (my $path = joinpath($self->root, 'perls', $name))) {
    +        require File::Basename;
    +        $name = File::Basename::basename(readlink $path);
    +    }
    +
        my $app = $class->new(
            qw(--quiet exec --with),
    -        $self->current_env,
    +        $name,
            'perl', '-MExtUtils::Installed', '-le',
            'BEGIN{@INC=grep {$_ ne q!.!} @INC}; print for ExtUtils::Installed->new->modules;'
        );

**Comment by y** [comment]
But maybe --exec should be a bit smarter and ignore aliases only when no explicit perls have been specified with --with. Right now you can't run `--exec --with alias`. I think that should be allowed.

**Comment by grr** [comment]
@gugod i just tested @y's patch and it works great. can you merge it, or resolve this anotherway?
