### ISSUE TITLE
Use of uninitialized value in split at /usr/share/perl5/App/perlbrew.pm line 1405.

### ISSUE THREAD

**Issue by varnie** [gugod/App-perlbrew#372]
I have perlbrew 0.43-1 installed (from the Ubuntu 12.10 packages).
It gives the following warning being run:

perlbrew switch perl-5.19.6
"Use of uninitialized value in split at /usr/share/perl5/App/perlbrew.pm line 1405."

I have perl v5.14.2 installed, if it helps.

Please write back.

**Comment by mperry2** [comment]
No response from the original reporter in two years. This ticket should probably be closed.

**Comment by gugod** [comment]
cool.. close this ticket.
