### ISSUE TITLE
Please add custom environment variable to specify shell

### ISSUE THREAD

**Issue by remorse** [gugod/App-perlbrew#388]
The environment that I'm in has a custom shell (PHSShell) which is executed even if I execute /bin/bash. The shell is, as far as I can tell, bash, just with a different name, and probably some kind of logging added. Unfortunately, the tests in `run_command_env` default to assuming `csh`, not `sh`. As a result, unless I manually override the `SHELL` variable every time I call `perlbrew`, it tries to run `csh`-style environment settings, which fail.

Please add something like `PERLBREW_SHELL` as an environment variable that I can set which overrides the built-in logic, so that those of us with odd shell names can (in extremis) make things work.

Thanks!

**Comment by mstreuhofer** [comment]
this is fixed in 0.72 - the issue can be closed

**Comment by erickpaquin** [comment]
@remorse . Can you close the PR please? Thanks.

**Comment by remorse** [comment]
Closing as requested...
