### ISSUE TITLE
App::Perlbrew install fails: Cwd.pm not found (OS X 10.9.2)

### ISSUE THREAD

**Issue by bwva** [gugod/App-perlbrew#389]
Setting up a new-to-me machine with a fresh install of OS X 10.9.2, App::Perlbrew fails to install because it can't find Cwd.pm. This seems to be because of the BEGIN block at the top of App::Perlbrew, which substitutes in a special list of directories for @INC. Unfortunately, that list doesn't include where OS X 10.9.2 locates Cwd.pm - in /Library/Perl/Updates/5.16.2/darwin-thread-multi-2level. I had to move Cwd.pm over to /Library/Perl/5.16/darwin-thread-multi-2level to get App::Perlbrew to install.

**Comment by gugod** [comment]
I'm closing this issue because it appears to me that no more effect are needed. Feel free to re-open it if that's not true.
