### ISSUE TITLE
/loader/../App/perlbrew.pm warning

### ISSUE THREAD

**Issue by jbolila** [gugod/App-perlbrew#399]
after one `perlbrew  self-upgrade` I'm getting the message:

`print() on closed filehandle $fh at /loader/0x9833690/App/perlbrew.pm line 1.`

after any perlbrew command, for any version of Perl.

I'm running a Arch Linux, some more details:

```
PERLBREW_VERSION=0.69
PERLBREW_PERL=18.2
PERLBREW_BASHRC_VERSION=0.67
```

**Comment by gugod** [comment]
I'm closing this issue because it appears to me that no more works are need for this issue. Thans everyone :)
