### ISSUE TITLE
"perlbrew switch" does not alter Perl version on Debian/Ubuntu

### ISSUE THREAD

**Issue by mcandre** [gugod/App-perlbrew#41]
Specs:

Debian 6 Squeeze and Ubuntu 10.10 Maverick

Trace:

```
$ sudo cpan
cpan> install App::Perlbrew
...
$ perlbrew install perl-5.12.1
...
$ perlbrew switch perl-5.12.1
$ perlbrew switch
Currently switched to perl-5.12.1
$ perl -v
5.10.1
```

Lies!!

**Comment by abuzarhamza** [comment]
I encountered the same issue on ubuntu 14.04 LTS .
though use `perlbrew use` command is working absolutely fine.

**Comment by KES777** [comment]
maybe this is related. I just now install `perl-5.26.1` 
Then install some modules [steps are here]()

But when return back to `perl-5.24.0` I got this error:

    lib/Sub/Metadata.c: loadable library and perl binaries are mismatched (got handshake key 0xd880000, needed 0xd600000)

I understand what that mean, but this should not happen because binary should be installed in different places. Libraries should be too.
