### ISSUE TITLE
manpath error for Perlbrew 0.7

### ISSUE THREAD

**Issue by zoot** [gugod/App-perlbrew#428]
The OS is Slackware64 14.1

The system Perl is 5.18.1

$ perlbrew --version
/usr/local/bin/perlbrew  - App::perlbrew/0.7

$ export PERLBREW_ROOT=~/.perlbrew
$ perlbrew init

$ source ~/.perlbrew/etc/bashrc
-su: manpath: command not found

The command manpath is not included in the man package for Slackware64 14.1:

http://packages.slackware.com/?r=slackware64-14.1&p=man-1.6g-x86_64-1.txz

**Comment by khaoz** [comment]
Same here. Perlbrew 0.72 Salckware 64 14.1

**Comment by khaoz** [comment]
Looking at the current perlbrew.pm source code i changed the line in my perl5/perlbrew/etc/bashrc from $(manpat) to $(manpath 2>/dev/null) and everything is working as expected

**Comment by gugod** [comment]
Closing this issue as it seems to be resolved already.
Thanks everyone.
