### ISSUE TITLE
cannot create standalone lib

### ISSUE THREAD

**Issue by mstreuhofer** [gugod/App-perlbrew#437]
perlbrew version 0.71

    $ perlbrew lib create test
    ERROR: '' is not installed yet, '@test' cannot be created.

**Comment by pwr22** [comment]
Whats the output of 

  perlbrew version
  perlbrew list

**Comment by mstreuhofer** [comment]
$ perlbrew version
/Users/manito/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.72

$ perlbrew list
  perl-5.005_04 (5.5.4)
  perl-5.8.9
  perl-5.10.1
  perl-5.10.1@scratch
  perl-5.16.3
  perl-5.18.4
  perl-5.20.1
  perl-5.20.1@module-install-repository
  perl-5.20.1@plack-middleware-docomoguid

---

it also happened with 0.71

**Comment by pwr22** [comment]
There is no asterix next to any Perl install so have you done a `perlbrew switch-off`? I ask because the man page makes it look like a lib without an install prefix is simply a shorthand for specifying the current install

I've just tried it myself and get the same error you got
    > perlbrew lib create test
    ERROR: '' is not installed yet, '@test' cannot be created.

Either specify an install prefix explicitly or switch over to one first

**Comment by mstreuhofer** [comment]
reading the docs (again) i see it now. it really is not clear that "perlbrew lib" depends on an installation being used or switched too unless the lib name includes an installation name. maybe the docs should be rewritten because most of it (beside a sentence at the very end) make it look like a lib without a perl-name is a free-agent lib which can be used in combination with any perl installation one has. beside the fact that this might not be a good idea (XS) it still seemed like this might be a feature.

**Comment by pwr22** [comment]
Perhaps so, feel free to improve the docs and send @gugod a pull request :P, besides that I think this issue can be closed

**Comment by mstreuhofer** [comment]
i'll let @gugod close this issue by merging my upcoming PR :-P
