### ISSUE TITLE
doc: Suggestion how to get a long name in "COMMAND: LIB" is inaccurate

### ISSUE THREAD

**Issue by mvuets** [gugod/App-perlbrew#440]
It's rather a very small problem, but it is a bit confusing. `perldoc perlbrew` page reads:

> COMMAND: LIB
> [...]
>    When "use"ing or "switch"ing to a lib, always provide the long name. A
>    simple rule: the argument to "use" or "switch" command **should appear in
>    the output of "perlbrew list"**.

But `perlbrew list` outputs **short names as well**:

```
$ perlbrew list
  perl-5.8.9
  perl-5.8.9@main
  perl-5.20.1
* perl-5.20.1@main
```

**Comment by mstreuhofer** [comment]
that's not short names and long names. they are both names. what the doc means is that you cannot use "perlbrew use perl-5.20.1" and expect it to actually use "perl-5.20.1@main". they both might point at a perl version 5.20.1 but the longer name refers to that perl installation while also activating the local::lib "main". in the first you would install modules in the hopefully pristine perl installation while in the second your modules would be installed in a completely different directory (thru the magic of local::lib) and thus can be nuked quite easily.

**Comment by mvuets** [comment]
You are right. I understand that behavior. My point is that the doc seems a bit confusing. And should be refined to reflect what you've said. I think I got confused by contradictory _'When "use"ing or "switch"ing to a lib, always **provide the long name**'_, while it's absolutely fine to provide both (just like you already said). Does that make more sense?

**Comment by Grinnz** [comment]
"to a lib" means to a local::lib, like `perl-5.20.1@main`. it i just saying you cannot switch to a lib by saying `perlbrew use main`.

**Comment by erickpaquin** [comment]
@mvuets , Can this issue be closed?

**Comment by mvuets** [comment]
@erickpaquin *shrug* Can't check now, nor in the near future-- I leave the decision up to you.

**Comment by erickpaquin** [comment]
@mvuets . I do not believe I have the permission to close this issue. Can you close it please? Thanks.

**Comment by mvuets** [comment]
Closed as per @erickpaquin's request.
