### ISSUE TITLE
Fish - perlbrew use of a new lib emits a warning

### ISSUE THREAD

**Issue by pwr22** [gugod/App-perlbrew#446]
This happens because the bin dir doesn't exist, it's harmless because it will be created if needed, but we probably don't want this to happen. The solution is to create the bin dir when creating a lib

    peter@dev ~> perlbrew switch 5.20.1@general
    set: Warning: path component /home/peter/.perlbrew/libs/5.20.1@general/bin may not be valid in PATH.
    set: No such file or directory

**Comment by gugod** [comment]
Can anyone confirm if this maybe related to this  RT issue ? https://rt.cpan.org/Ticket/Display.html?id=104048

/cc @yanick

**Comment by yanick** [comment]
I think it is. Checking in more details now.

**Comment by yanick** [comment]
Yup, seems to have been introduced in 22de65e4

I'll try to come up with a patch this week-end. And see of a way to test all of that somehow.
