### ISSUE TITLE
$MANPATH

### ISSUE THREAD

**Issue by kostya-ten** [gugod/App-perlbrew#449]
perlbrew switch perl-5.20.1

manpath: warning: $MANPATH set, ignoring /etc/manpath.config
manpath: warning: $MANPATH set, ignoring /etc/manpath.config

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"

Version - App::perlbrew/0.72

**Comment by autarch** [comment]
I think the fix for this is to execute `mathpath` with the `-q` flag.

**Comment by gugod** [comment]
Hmm, I don't see this warning on my Ubuntu installation (but it is a 15.10) with perlbrew 0.70 -- I guess it's OK to close this isuse. Feel free to re-open if you still see it happening. Thanks :)
