### ISSUE TITLE
Get an error with switch command 

### ISSUE THREAD

**Issue by skarfacegc** [gugod/App-perlbrew#451]
- App::perlbrew/0.73
- OSX Yosemite 10.10.2
- zsh 5.0.5 (x86_64-apple-darwin14.0)
- using zprezto (modified to load perlbrew from the perl module using the following)

```
# Load up perlbrew
if [ -e ~/perl5/perlbrew/etc/bashrc ]
then
        source ~/perl5/perlbrew/etc/bashrc
fi
```

Verified that I wasn't calling perlbrew twice  (grep -r in my zsh dir)

`__perlbrew_reinit:5: file exists: /Users/xxxxx/.perlbrew/init`

Everything appears to work correctly (I'm not using libs) but the shell error is annoying.

**Comment by skarfacegc** [comment]
Appears to be an issue with noclobber and zsh.  I tried adding  a ! to each of the places where I see an echo > into that file  (I think I found 3 places).  Didn't seem to do anything.

**Comment by gugod** [comment]
Nice catch! Thanks @skarfacegc and @mstreuhofer !
