### ISSUE TITLE
Install perl 5.20.2 failed in MAC OS X Yosemite 10.10.3 (14D136)

### ISSUE THREAD

**Issue by dantesun** [gugod/App-perlbrew#464]
perlbrew install -j 5 --as  5.20.2 --thread --64all -Duseshrplib perl-5.20.2
Installing /Users/dsun/perl5/perlbrew/build/perl-5.20.2 into ~/perl5/perlbrew/perls/5.20.2

This could take a while. You can run the following command on another shell to track the status:

  tail -f ~/perl5/perlbrew/build.perl-5.20.2.log

Installation process failed. To spot any issues, check

  /Users/dsun/perl5/perlbrew/build.perl-5.20.2.log

If some perl tests failed and you still want install this distribution anyway,
do:

  (cd /Users/dsun/perl5/perlbrew/build/perl-5.20.2; make install)

You might also want to try upgrading patchperl before trying again:

  perlbrew install-patchperl

Generally, if you need to install a perl distribution known to have minor test
failures, do one of these command to avoid seeing this message

  perlbrew --notest install perl-5.20.2
  perlbrew --force install perl-5.20.2

 [dsun@DantedeMacBook-Pro ~]$ tail /Users/dsun/perl5/perlbrew/build.perl-5.20.2.log
* Can't find string terminator "FILE_PATH" anywhere before EOF at /Users/dsun/perl5/perlbrew/bin/patchperl line 27245. *

**Comment by gugod** [comment]
This works for me. From the log I think it'll be fixed my re-installing patchperl. please retry after running this:

    perlbrew install-patchperl

**Comment by dantesun** [comment]
It worked after resintall patchperl
