### ISSUE TITLE
Bioperl

### ISSUE THREAD

**Issue by francicco** [gugod/App-perlbrew#469]
I'm not able to install Bio::Perl can someone help me please?

Best
F

Test Summary Report
-------------------
t/SeqIO/Splicedseq.t                 (Wstat: 512 Tests: 1 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 19 tests but ran 1.
t/Tree/TreeIO/nexml.t                (Wstat: 512 Tests: 4 Failed: 0)
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 46 tests but ran 4.
Files=334, Tests=19015, 358 wallclock secs ( 3.23 usr  0.72 sys + 110.45 cusr 16.03 csys = 130.43 CPU)
Result: FAIL
Failed 2/334 test programs. 0/19015 subtests failed.

**Comment by sestaton** [comment]
This is unrelated to perlbrew. It would be better to post this on the [BioPerl issue tracker](https://github.com/bioperl/bioperl-live/issues) or on the BioPerl listserv.

You may want to show the specific output of those failing tests when you report the issue. It could be a dependency issue or perhaps something you can just ignore.

**Comment by gugod** [comment]
I'm just closing this issue since that is not really actionalble. Thanks to all.
