### ISSUE TITLE
installation message: You need to find a working C compiler

### ISSUE THREAD

**Issue by CarlosVaras** [gugod/App-perlbrew#473]
I really want to use perlbrew, but the gcc prerequisite sucks.
It's not real obvious how to get gcc installed and running.

(cd /objdir; srcdir/configure) fails with "cannot create executables".
config.log shows gcc trying to compile the first text file in the / directory(?!)

I'll have to try another compiler, I guess. Can't somebody in the Linux community come up with a sane process for installing software? Could perlbrew provide a binary install instead?

I have been working with Unix for years, but no wonder Linux adoption is so limited.

**Comment by gugod** [comment]
What linux distribution are you using ? gcc/clang should be installable as binary packages on most of linux distributions.

**Comment by CarlosVaras** [comment]
Thanks for the reply. The OS identifies itself (uname -a) as Mandrake Gnu/Linux. I forget the version right now because I did not install the OS. I was able to download and install gcc. But now I am having to learn about and debug the zillion "configure" options in gcc. I know enough about Unix and Linux to know it's not about permissions. But, if you look at it from a user/developer p.o.v., I think your product is what I need. Yet, I cannot install/run it without dealing with gcc which is another can of worms. I understand and support the Linux/Unix philosophy of building blocks, but I wish it was easier to get things going. I am having to use Perlbrew, because I am worried about (and had difficulties) updating the Perl version that came with the OS. Why should this be the case? I applaud what you've done to support multiple Perl versions on the same OS install. I question the architecture that required you to create this solution. The mess that is Linux today is not your problem, I understand. Sadly, gcc and its documentation is not for the faint of heart. Cheers!

**Comment by gugod** [comment]
iirc Mandrake uses rpm for binary package management, does `rpm -i gcc` install gcc by any chance ? I'm not familiar with rpm command myself and that was just something gisted from http://manpages.ubuntu.com/manpages/vivid/en/man8/rpm.8.html 

I hope that helps.

**Comment by Grinnz** [comment]
RPM is package management but will not find packages from a repository. Mandriva uses urpmi or rpmdrake for downloading from repositories. I am not sure if the version you are using would use that.

gcc is a requirement of perlbrew because you need a C compiler to build perl (which is what perlbrew install does). Many perl packages also contain C code to compile, but for just installing pure-perl CPAN modules it is not needed. (however, `make` is needed for most)

**Comment by LubosKolouch** [comment]
I think this should be closed as it’s required...
