### ISSUE TITLE
Can't locate Getopt/Long.pm in @INC (@INC contains: FatPacked::10738960=HASH(0xa3dd10)

### ISSUE THREAD

**Issue by rlauer6** [gugod/App-perlbrew#483]
$ wget -O - http://install.perlbrew.pl | bash
--2015-09-18 13:07:02--  http://install.perlbrew.pl/
Resolving install.perlbrew.pl (install.perlbrew.pl)... 217.70.184.38
Connecting to install.perlbrew.pl (install.perlbrew.pl)|217.70.184.38|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://raw.githubusercontent.com/gugod/App-perlbrew/master/perlbrew-install [following]
--2015-09-18 13:07:03--  https://raw.githubusercontent.com/gugod/App-perlbrew/master/perlbrew-install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.46.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1254 (1.2K) [text/plain]
Saving to: ‘STDOUT’

 0% [                                                                               ] 0           --.-K/s              
## Download the latest perlbrew

100%[==============================================================================>] 1,254       --.-K/s   in 0s      

2015-09-18 13:07:03 (76.9 MB/s) - written to stdout [1254/1254]
## Installing perlbrew

Can't locate Getopt/Long.pm in @INC (@INC contains: FatPacked::10738960=HASH(0xa3dd10) /usr/share/perl5 /usr/lib64/perl5 /usr/local/share/perl5 /usr/local/lib64/perl5) at perlbrew-10275 line 33.
BEGIN failed--compilation aborted at perlbrew-10275 line 33.
Compilation failed in require at perlbrew-10275 line 5795.
BEGIN failed--compilation aborted at perlbrew-10275 line 5795.

**Comment by gugod** [comment]
Hi @rlauer6 , I'm guessing you are using some RedHat-ish Linux. If that's the case, I believe this issue is the same as #409 , which is solved with the latest release. If you repeat the installation process it should work now.

**Comment by Shicheng-Guo** [comment]
works or not? 
```
export PERL5LIB=$PERL5LIB:/home/shg047/perl5/perlbrew/Getopt-Long-2.48/lib/
export PERLLIB=$PERLLIB:/home/shg047/perl5/perlbrew/Getopt-Long-2.48/lib/

```

**Comment by gugod** [comment]
@Shicheng-Guo can you elaborate more about you  problem please ?

**Comment by gugod** [comment]
I'm closing this issue since there hasn't been any follow-ups. Feel free to re-raise it if it still occurs.
