### ISSUE TITLE
HELLPPP!! perlbrew setup and working.

### ISSUE THREAD

**Issue by kraken17** [gugod/App-perlbrew#490]
When I test a setup in ssh the module Crypt::SSLeay is present and seems to be working.

When I do a test PL script that came with my Actinic Software, and point all the perl includes to the correct path, the response back from the apache server is that Crypt::SSLeay (and all the other modules that I have installed) is not installed. 

Please help me resolve this.

**Comment by gugod** [comment]
@kraken17 Hi, do you still need help on this issue ? How does it related to perlbrew ?
