### ISSUE TITLE
patchperl causes test failures during build

### ISSUE THREAD

**Issue by MSK61** [gugod/App-perlbrew#491]
When I use the command
`perlbrew install <path-to-perl-checkout>`
to install perl from a checked-out blead sources, the build doesn't complete successfully due to the failure of two tests in perl test suite as indicated by perlbrew log file ~/perl5/perlbrew/build.perl-5.23.4.log.

> Mohammed El-Afifi  <mohammed_elafifi@yahoo.com> not found in AUTHORS
porting/authors.t .................................................
Failed 1/991 subtests
>
Mohammed El-Afifi  <mohammed_elafifi@yahoo.com> not found in AUTHORS
porting/pending-author.t ..........................................
Failed 1/1 subtests

More investigation revealed that patchlevel.h in the top directory of perl blead sources was modified by patchperl like this:

>    diff --git a/patchlevel.h b/patchlevel.h
   index dd28c67..d9ce11e 100644
   --- a/patchlevel.h
   +++ b/patchlevel.h
   @@ -137,6 +137,7 @@ static const char * const local_patches[] = {
           ,"uncommitted-changes"
    #endif
           PERL_GIT_UNPUSHED_COMMITS       /* do not remove this line */
   \+       ,"Devel::PatchPerl 1.38"
           ,NULL
    };

Although no other source files have ever been touched by patchperl. This causes the failing tests to be paranoid about my name and email(retrieved from my git configuration attributes user.name and user.email) not being found in the AUTHORS file.

I understand that this might be a problem of Devel::PatchPerl in its own and have accordingly filed an issue against it [here](https://rt.cpan.org/Public/Bug/Display.html?id=108689) and [here](https://github.com/bingos/devel-patchperl/issues/22). However after a discussion with some perl porter over \#p5p IRC, it was concluded that some option for perlbrew install command that will skip patching altogether with an explicitly specified checkout directory would be nice to have.

I'd like to know if this's possible and makes sense or if we should solely rely on a fix in Devel::PatchPerl.

**Comment by gugod** [comment]
patchperl is invoked by default because it does help in many cases. I guess it could be opt-out with an installation option (like `perlbrew install --no-patchperl `)

**Comment by MSK61** [comment]
@gugod From perlbrew documentation here https://metacpan.org/pod/perlbrew#COMMAND:-INSTALL I think there's no such option currently available, so I guess you mean it can be added in a future release of perlbrew.

**Comment by gugod** [comment]
Yes that's exactly what I meant. Sorry for not making it clear.

**Comment by MSK61** [comment]
Will it be more convenient to activate this option automatically in blead installation mode `perlbrew install blead` as building from blead sources mayn't succeed otherwise(unless testing is skipped with `-n`)?

**Comment by gugod** [comment]
If it's automatically opt-in, then in some use cases people might want to opt-out. vice versa. IMHO it's better to keep optional behavoiur consistent.
