### ISSUE TITLE
Module::Install::AuthorRequires needed for author_requires

### ISSUE THREAD

**Issue by djzort** [gugod/App-perlbrew#496]
Without Module::Install::AuthorRequires installed, i get:

$ perl Makefile.PL 
include /home/dean/git/github/App-perlbrew/inc/Module/Install.pm
String found where operator expected at Makefile.PL line 30, near "author_requires
    'Pod::Markdown'"
    (Do you need to predeclare author_requires?)
syntax error at Makefile.PL line 30, near "author_requires
    'Pod::Markdown'"
Execution of Makefile.PL aborted due to compilation errors.

Im not certainly how to correctly articulate that this is needed in the module metadata?

**Comment by gugod** [comment]
AuthorRequires.pm is part of the tarball `inc/Module/Install/AuthorRequires.pm` which should be OK for users who are installing via cpan/cpanm. It looks like you are running `perl Makefile.PL` from a git working copy, then you need to just install the module `Module::Install::AuthorRequires` first.

**Comment by erickpaquin** [comment]
@djzort , is this still an issue for you? If not we should close this PR as it is over 7 years old by now. Thanks.
