### ISSUE TITLE
-U uselargefiles should be -D uselargefiles

### ISSUE THREAD

**Issue by abraxxa** [gugod/App-perlbrew#498]
perlbrew help install displays:

    -D,-U,-A       Switches passed to perl Configure script.
                   ex. C<perlbrew install perl-5.10.1 -D usemymalloc -U uselargefiles>

perlbrew version 0.74

**Comment by gugod** [comment]
Thank you for noticing. I chose different symbol just for the purpose of showing how to use these flags.
