### ISSUE TITLE
Is it meaningful to have --nonotest option?

### ISSUE THREAD

**Issue by MSK61** [gugod/App-perlbrew#506]
I just noticed that the --notest option supports negation, so --nonooption can be specified. I think it's a bit confusing for a user, given that the default is already to run the tests if the --notest option is missing. A suitable resolution for this may be to either disable the negation form, or to change the option to --test(and keep the negation form). I think the former approach is easier as the latter might be breaking change.

**Comment by gugod** [comment]
That's probably a mis-feature because there really is only 2 possible state (test vs notest) instead of 3 (test vs notest vs undefined)

**Comment by gugod** [comment]
e4526d1e3ee9732697c45a9de13f22a66a620fa0 removed `--nonotes`. Case closed! :)
