### ISSUE TITLE
Install script fails due to recent change

### ISSUE THREAD

**Issue by yoshizow** [gugod/App-perlbrew#514]
```
\curl -L https://install.perlbrew.pl | bash
## Download the latest perlbrew
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

The reason is that `$LOCALINSTALLER` is now used before it is defined by this change: https://github.com/gugod/App-perlbrew/commit/8e89fe0f0a2d8da86ffeac524cf0951bbb31bf5e

**Comment by gugod** [comment]
*facepalm*
Thanks for reporting.
I simply reverted that commit.
