### ISSUE TITLE
No longer able to brew blead

### ISSUE THREAD

**Issue by ribasushi** [gugod/App-perlbrew#523]
After a recent upgrade the abbrev-length of the git repo snapshot changed. It is currently at 10 characters:

```
~$ curl -s http://perl5.git.perl.org/perl.git/snapshot/blead.tar.gz | tar -zt | head -n 3
perl-2c2284d8d8/
perl-2c2284d8d8/.dir-locals.el
perl-2c2284d8d8/.gitignore
```

This in turn prevents [the `{7,8}$` on this line](https://github.com/gugod/App-perlbrew/blob/develop/lib/App/perlbrew.pm#L1154) from matching, leading to a failure to `cd` and an abort due to `patchperl` exitting with an error.

**Comment by ribasushi** [comment]
As @seveas mentioned elsewhere:
> that code is fundamentally broken. the snapshot sha1 abbrev length can be anything from 4 to 40

**Comment by seveas** [comment]
I've configured perl5.git.perl.org to use 7-character abbreviations now, but want to undo that again asap. Git's new default is to auto-calculate the abbreviation length based on the amount of objects in the repo, and for an old and busy project like perl that's apparently 10.

**Comment by seveas** [comment]
See also https://github.com/gugod/App-perlbrew/pull/524

**Comment by DrHyde** [comment]
@seveas's patch in a comment on #524 appears to work

**Comment by glasswalk3r** [comment]
See #583 , newer version 0.82 fix that.

**Comment by toddr** [comment]
So this ticket can be closed?

**Comment by davidcantrelluk2** [comment]
I'd say so:

```
$ perlbrew self-upgrade
  perlbrew is installed: ~/perl5/perlbrew/bin/perlbrew
  perlbrew root (~/perl5/perlbrew) is initialized.
$ perlbrew install blead
  ...
perl-blead is successfully installed.
```
