### ISSUE TITLE
perlbrew wants me to fiddle with non-existent scripts

### ISSUE THREAD

**Issue by DrHyde** [gugod/App-perlbrew#525]
I just did a self-upgrade, and ...

```
Append the following piece of code to the end of your ~/.bash_profile and start a
new shell, perlbrew should be up and fully functional from there:

source ~/perl5/perlbrew/etc/bashrc
```

but I don't have a .bash_profile. I have a .profile, and because this is a self-upgrade it already contains the magic incantation. I think perlbrew should be a bit more intelligent about this, both when upgrading and on first install!

**Comment by zbentley** [comment]
The PR referenced above may fix your issue @DrHyde. Please give it a spin and let me know if it does! 

Be aware that if you update from current Perlbrew to the version in that PR, the issue will *not* disappear; it's only `self-upgrade`s  _after you're already on that PR's changes_ that should work.

**Comment by gugod** [comment]
Thank to @zbentley, the instruction message is now shorter when you do a self-upgrade :)

**Comment by DrHyde** [comment]
I'm not currently on a machine with perlbrew but that certainly looks like it'll do the job. Thanks @zbentley.
