### ISSUE TITLE
perlbrew - from tcsh to bash

### ISSUE THREAD

**Issue by marek-step** [gugod/App-perlbrew#530]
Hello all!

I switched from tcsh to bash (on actual MacOS). I am unable to source perlbrew. I put in my ~/.bash_profile following code: 

`if [[ -f $HOME/perl5/perlbrew/etc/bashrc ]]; then
    source $HOME/perl5/perlbrew/etc/bashrc
fi`

But my Terminal is starting (as bash) with 

`-bash: setenv: command not found
$ which perl
perl is /usr/bin/perl
`

The command perlbrew is in the path

`
$ perlbrew list
  perl-5.18.4
  perl-5.23.4
`

Any help? Thank you in advance!

marek

**Comment by gugod** [comment]
Hi @marek-step 

You are seeing this "setenv" message because the file `~/.perlbrew/init` contains statements prepared for csh -- you can run `perlbrew reinit` to re-generate it for bash. Alternatively, delete that file and run `perlbrew switch perl-5.18.4` should also regenerate that file.

**Comment by marek-step** [comment]
Thank you gugod!

perlbrew seems not to know the command "reinit"

`
$ perlbrew reinit

Unknown command: `reinit`. Did you mean `init`?
`
the switch command is working, but is not permanent after restart:

`
perlbrew switch perl-5.23.4

which perl

/Users/mstep/perl5/perlbrew/perls/perl-5.23.4/bin/perl
`

An idea, what to do?

**Comment by gugod** [comment]
@marek-step I probably mistakenly think that "reinit" is a command. (There is a bash function defined by perlbrew, but perhaps only used internally). Re-run `perlbrew init` should do the trick as well.

I am curious why `switch` failed to keep the setting -- it should override `~/.perlbrew/init` with a bunch of `PERLBREW_` -prefixed variables that reflect to the version we're switching to. This file is a shell script that matches your `$SHELL` variable. If you are using bash, then it should be a list of `export` statements. If you're using csh, then it should contain a list of `setenv` statements.

If your new shell/terminal lost perlbrew context, does it work after you manually run (after launching a new terminal):

    source ~/perl5/perlbrew/etc/bashrc

... if so, that means the content of `~/.bash_profile` is not invoked by the bash that are launched within your terminal app. bash reads `.bash_profile` when it is login shell, but avoids it on when it is not invoked as a login shell. You can try put that into `.bashrc` -- basically you want that to be executed as late as possible, ideally right before you see shell prompt.

**Comment by marek-step** [comment]
Thank you gugod!

Everything works now! Only switching to my old tcsh provokes an ugly (five times):

`$ tcsh
export: Command not found.`

This is issued by the ~/.perlbrew/init

`% cat ~/.perlbrew/init
# DO NOT EDIT THIS FILE
export PERLBREW_MANPATH="/Users/mstep/perl5/perlbrew/perls/perl-5.23.4/man"
export PERLBREW_PATH="/Users/mstep/perl5/perlbrew/bin:/Users/mstep/perl5/perlbrew/perls/perl-5.23.4/bin"
export PERLBREW_PERL="perl-5.23.4"
export PERLBREW_ROOT="/Users/mstep/perl5/perlbrew"
export PERLBREW_VERSION="0.76"`

**Comment by marek-step** [comment]
Sorry! Back again!

the sourcing ~/perl5/perlbrew/etc/bashrc creates still an error! 

`-bash: setenv: command not found`

five times! But an `setenv` command is not found in ~/perl5/perlbrew/etc/bashrc

I made a `perlbrew init` several times ...

Thank you for your patience

marek

**Comment by marek-step** [comment]
Solution as gugod suggested: 

`cd ./perl5/perlbrew/etc/
mv bashrc bashrc_out
perlbrew init`

restart of Terminal ... Uff!

**Comment by marek-step** [comment]
Sorry the last command was probably: 

`perlbrew switch perl-5.25.6`

Thank you again for your help!

marek
