### ISSUE TITLE
mention a perlbrew install via sparrow

### ISSUE THREAD

**Issue by melezhik** [gugod/App-perlbrew#537]
Hi @gugod !

I recall once I created a sparrow plugin to bootstrap perlbrew on linux boxes -  https://perlbrew.pl/Release-0.76.html , could we mention this at some perlbrew docs, so that people would know?

Thanks

Alexey

**Comment by gugod** [comment]
Hi @melezhik,

Absolutely. If you already have some materials, feel free to paste into the github wiki of this project:

    https://github.com/gugod/App-perlbrew/wiki

This wiki is the data source of https://perlbrew.pl website -- I manually re-generate the site each time I made a perlbrew release (could've make a bot for this)

Either a link to your existing doc page, or a new wiki page that has some content.

**Comment by melezhik** [comment]
Hi @gugod ! Great. What wiki  page do you recommend to place my content? I have not find an INSTALL perlbrew page there ...

A link to sparrow plguin to install perlbrew is here - https://github.com/melezhik/perlbrew

Currently it is just a wrapper for perlbrew bootstrap with minimal checks for ~/perl5/perlbrew/etc/bashrc patch line

**Comment by gugod** [comment]
@melezhik the installation is petty much in the 'index' page. Perhaps you could create
a new page named like 'Installation vis Sparrow' , and update index page to link to there.

**Comment by melezhik** [comment]
Done. https://github.com/gugod/App-perlbrew/wiki/index#install-other-ways

**Comment by gugod** [comment]
@melezhik Great! I've rebuild the site as well :) https://perlbrew.pl/

**Comment by melezhik** [comment]
Thank you very much!

2016-12-08 12:05 GMT+03:00 Kang-min Liu <notifications@github.com>:

**Comment by melezhik** [comment]
Hi @gugod ! How can I find an information added to perlbrew site ? I want to look at sparrow section )))

**Comment by melezhik** [comment]
ahh it should be there - https://perlbrew.pl/ ... can't find my info there , have you rebuilt site?

**Comment by gugod** [comment]
@melezhik Sorry to come back on this this late. The site is now rebuild.

**Comment by melezhik** [comment]
Hi @gugod , this is a good news, thanks! Hopeful people will find the information helpful. 
Regards.
