### ISSUE TITLE
Getting error downloading with apt version of perlbrew

### ISSUE THREAD

**Issue by cmdcolin** [gugod/App-perlbrew#552]
I tried under lubtuntu 16 to use `sudo apt install perlbrew`, got 0.78-1 version, and it would give errors for downloading all perl releases I tried

```
Fetching perl 5.16.0 as /home/cdiesh/perl5/perlbrew/dists/perl-5.16.0.tar.bz2
Download http://www.cpan.org/authors/id/R/RJ/RJBS/perl-5.16.0.tar.bz2 to /home/cdiesh/perl5/perlbrew/dists/perl-5.16.0.tar.bz2
ERROR: Failed to download http://www.cpan.org/authors/id/R/RJ/RJBS/perl-5.16.0.tar.bz2
```

I installed perlbrew via the recommended website way, e.g. `\curl -L https://install.perlbrew.pl | bash` and then it downloaded releases fine

Not sure if issue should be filed here as it seems to clearly be a problem with the apt package only but thought I'd see

**Comment by dpchris** [comment]
I got the same error, Did you find anything ?

**Comment by cmdcolin** [comment]
Installing from the curl instructions from https://perlbrew.pl/ worked for me

**Comment by gugod** [comment]
This is really odd. There shouldn't be any functianilyt difference. The downloading part invokes external commands (curl/wget/fetch) anyway.... @dpchris did you also use lubuntu ?

Is it possible that this is some proxy issue that is somehow only visible with the apt-version of perlbrew ?

**Comment by linusnielsen** [comment]
Late to the game. I had the same issue, but running `perlbrew init` solved the problem. After that, the download worked.

**Comment by gugod** [comment]
I'm closing this issue as I'm not sure what to follow-up on the discussion here. :) feel free to re-open when we have more clue.
