### ISSUE TITLE
"perlbrew install stable" (5.24.1) fails tests on OpenBSD 6.1

### ISSUE THREAD

**Issue by rage311** [gugod/App-perlbrew#553]
On OpenBSD 6.1 with the GENERIC.MP amd64 kernel.

Installed perlbrew using:
`$ ftp -o- https://install.perlbrew.pl | sh`
Prepended `$HOME/perl5/perlbrew/bin` to `$PATH`
`$ source ~/perl5/perlbrew/etc/bashrc` (in zsh)
`$ perlbrew install stable` cranks for ~10 minutes (i5-4300U), then fails due to some sigaction.t tests:

````
#   Failed test 'SA_SIGINFO got right pid'
#   at t/sigaction.t line 222.
#          got: '0'
#     expected: '45602'

#   Failed test 'SA_SIGINFO got right uid'
#   at t/sigaction.t line 222.
#          got: '0'
#     expected: '1000'
# Looks like you failed 2 tests of 36.
../ext/POSIX/t/sigaction.t ........................................ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/36 subtests 
        (less 4 skipped subtests: 30 okay)

<snip>

Test Summary Report
-------------------
../ext/POSIX/t/sigaction.t                                      (Wstat: 512 Tests: 36 Failed: 2)
  Failed tests:  32, 34
  Non-zero exit status: 2
Files=2410, Tests=850458, 757 wallclock secs (65.31 usr 30.86 sys + 382.83 cusr 86.57 csys = 565.57 CPU)
Result: FAIL
*** Error 2 in /home/$USER/perl5/perlbrew/build/perl-5.24.1 (makefile:837 'test_harness')
##### Brew Failed #####
````

I ran `$ perlbrew install-patchperl` as suggested in the failed build output text, but still no luck.  After failing several times, I did a `make install` in the given build directory and it installed just fine and appears to be working so far, but I'd like to help get this fixed.

This is my first time attempting to use perlbrew, so I might be doing something else wrong here.  Please let me know if I can provide any more information.

**Comment by skaji** [comment]
It seems that this is a known issue https://rt.perl.org/Public/Bug/Display.html?id=129895

**Comment by rage311** [comment]
Ah, thanks for helping to get to the bottom of this.  Looks like it's an issue with some POSIX tests when building Perl on OpenBSD then.  It can be closed here.

**Comment by gugod** [comment]
closed as this is not really a perlbrew issue :)
