### ISSUE TITLE
When home dir is not /home/$user

### ISSUE THREAD

**Issue by apelin20** [gugod/App-perlbrew#554]
Hello,

It just so happens that the machine I am using does not house all home dirs in /home. It's a long story...

Anyways, I have looked through your scripts and it seems all installations are guided to /home

Is there any way to install in an alternate location?

Thanks,
Adrian

**Comment by skaji** [comment]
Does PERLBREW_ROOT work for you?

**Comment by gugod** [comment]
@apelin20, following what @skaji said, PERLBREW_ROOT is an env set you can set at installation time, or in bashrc.

Depending on your setup, you may or may not need to set PERLBREW_HOME as well.

Read the section of CONFIGURATION in perlbrew document from `perldoc perlbrew`, or here:

     https://metacpan.org/pod/perlbrew#CONFIGURATION

There are more description in detail.

If this is still not enough, let us know what's missing.

Cheers.

**Comment by apelin20** [comment]
Perfect, sorry for the bother, I couldn't find the Docs

**Comment by gugod** [comment]
@apelin20 no worries. Thanks for asking :)
