### ISSUE TITLE
cpanm installed by perlbrew try to use different version

### ISSUE THREAD

**Issue by KES777** [gugod/App-perlbrew#556]
I have install perl-5.24.1 with perlbrew:

```
$ alias pb perlbrew
$ pb list
  perl-5.24.1
$ pb available
  perl-5.27.0
  perl-5.26.0
i perl-5.24.1
  perl-5.22.3
  perl-5.20.3
  perl-5.18.4
  perl-5.16.3
  perl-5.14.4
  perl-5.12.5
  perl-5.10.1
  perl-5.8.9
  perl-5.6.2
  perl5.005_04
  perl5.004_05
```

Then install `cpanm`:
```
$ pb install-cpanm 

cpanm is installed to

    /home/kes/perl5/perlbrew/bin/cpanm

$ which cpanm
/home/kes/perl5/perlbrew/bin/cpanm
```

Trying to install something with `cpanm` I got:

```
$ cpanm carton
!
! Can't write to /usr/local/share/perl/5.22.1 and /usr/local/bin: Installing modules to /home/kes/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl/5.22.1 and /usr/local/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
! Finding carton on cpanmetadb failed.
^C
```

Because I am using `perl-5.24.1` I do not expect that something will write to `perl/5.22.1`

So I look into environment:
```
$ env | grep PERL
PERLBREW_BASHRC_VERSION=0.78
PERLBREW_ROOT=/home/kes/perl5/perlbrew
PERLBREW_HOME=/home/kes/.perlbrew
PERLBREW=command perlbrew
```

After use right version of perl the error has gone:
```
$ pb use perl-5.24.1 
$ env | grep PERL
PERLBREW_VERSION=0.78
PERLBREW_PERL=perl-5.24.1
PERLBREW_BASHRC_VERSION=0.78
PERLBREW_ROOT=/home/kes/perl5/perlbrew
PERLBREW_HOME=/home/kes/.perlbrew
PERLBREW_MANPATH=/home/kes/perl5/perlbrew/perls/perl-5.24.1/man
PERLBREW_PATH=/home/kes/perl5/perlbrew/bin:/home/kes/perl5/perlbrew/perls/perl-5.24.1/bin
PERLBREW=command perlbrew
$ which cpanm
/home/kes/perl5/perlbrew/bin/cpanm
$ cpanm carton
! Finding carton on cpanmetadb failed.
! Finding carton () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution carton
```

It seems that perlbrew version of `cpanm` should be restricted to install modules only to brew's perl and do not try to install into system.

**Comment by gugod** [comment]
@KES777

**Comment by gugod** [comment]
@KES777 ,

> It seems that perlbrew version of cpanm should be restricted to install modules only to brew's perl and do not try to install into system.

It is indeed to work like this. I don't think  `cpanm` behaviour has changed recently. However, if for some reason the sheban of your `cpanm` points to your system perl, than it will behave behave like this. The sheban line of cpanm should be using `env perl`, like mine:

    > head =cpanm
    #!/usr/bin/env perl

OTOH, I suggest you to try installing some dependency-free modules, suchas `Mo`, just to eliminate the fact that's not something special about Carton. (btw `carton` is not indexed by cpanmetadb, it needs to be `Carton`)

**Comment by KES777** [comment]
I MUST `switch` or `use` from system perl to get it work.
sorry, that is my fault. I occasionally thoughts that cpnam from perlbrew should install into perlbrew.

**Comment by gugod** [comment]
Oh that's why. Perhaps the instructurion was still ambiguate. Thanks for the explanation. :)

FYI in order to let `cpanm` work with `use` / `switch` command, the `cpanm` executable MUST be using `env perl` shebang instead of a hard-coded perl path. If effectively the `env perl` is the system perl, that reproduce your test cases.

It is still possible to resolve it by installing a copy of `cpanm` executable to all perl installations, with different hard-coded shebang for each one, and remove the current global-ish `cpanm` executable. This way, when perllbrew is inactive, the `cpanm` executable in PATH should not be the one that's installed via perlbrew.

**Comment by KES777** [comment]
> when perllbrew is inactive, the cpanm executable in PATH should not be the one that's installed via perlbrew.

No, when perlbrew is not activated yet the perlbrew `cpanm` is on `PATH`

```
$ which cpanm
/home/kes/perl5/perlbrew/bin/cpanm
$ env | grep PATH
MANPATH=/home/kes/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
PATH=/home/kes/perl5/perlbrew/bin:/home/kes/bin:/home/kes/bin:/home/kes/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
PERLBREW_PATH=/home/kes/perl5/perlbrew/bin
WINDOWPATH=8
$ pb list
  perl-5.24.1
$ perl -v

This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 58 registered patches, see perl -V for more detail)

```
