### ISSUE TITLE
Wrong version in META.yml in 0.79 release.

### ISSUE THREAD

**Issue by pink-mist** [gugod/App-perlbrew#557]
The version in the META.yml file is specified as version 0.78 in the release of version 0.79:

https://metacpan.org/source/GUGOD/App-perlbrew-0.79/META.yml#L43

This should clearly have been updated to 0.79 ... I can't seem to find the META.yml as a file in git, so I assume it's generated from something? That something ought to be fixed so it sets the correct version.

(This bugreport was also sent to bug-App-perlbrew@rt.cpan.org - https://rt.cpan.org/Public/Bug/Display.html?id=122279 - but I wanted to report it here as well since this seems to have more traffic)

**Comment by gugod** [comment]
Thank you very much @pink-mist , it looks like I've made a mistake with my usual releasing process. I will just make a new release and delete this one on CPAN :)

**Comment by gugod** [comment]
0.80 is released with correct version number in META.yml
