### ISSUE TITLE
Sort order changed for the 'list' command

### ISSUE THREAD

**Issue by dur-randir** [gugod/App-perlbrew#574]
Commit c9ec7a54723b410d3ff78ce6d0c190fb3e549819 (and corresponding pull request) only mentions sorting output of the 'available' command. But now the 'list' command follows the same rules, compare before:

```
% perlbrew list
  perl-5.6.2
* perl-5.8.8-dbg
  perl-5.8.9-dbg
  perl-5.10.0
  perl-5.10.1
  perl-5.10.1-thr
  perl-5.20.2
  perl-5.20.2-thr-dbg
  perl-5.22.1
  perl-5.22.1-thr-dbg
  perl-5.24.1
  perl-5.24.1-thr-dbg
  perl-5.26.0
  perl-5.26.0-thr-dbg
```

with after:
```
% perlbrew list
  perl-5.26.0
  perl-5.26.0-thr-dbg
  perl-5.24.1
  perl-5.24.1-thr-dbg
  perl-5.22.1
  perl-5.22.1-thr-dbg
  perl-5.20.2
  perl-5.20.2-thr-dbg
  perl-5.10.1
  perl-5.10.1-thr
  perl-5.10.0
  perl-5.8.9-dbg
* perl-5.8.8-dbg
  perl-5.6.2
```

Was this change intentional?

**Comment by fluca1978** [comment]
The change was intentional and made to make the two lists comparable and coherent each other.

**Comment by dur-randir** [comment]
While I have no particular opinion on the 'available' sorting, but I think that the 'list' should still be oldest-to-newest - as most commonly you'd install and iterate over fresher perls and installed lists can be quite long (I've shown only half of mine), so it's a bit annoying now to scroll to the top.

**Comment by fluca1978** [comment]
I did that for the very opposite reason, i.e., having most recent first.
I believe we can either list them (coherently) sorted in one version or another, but have an extra line option 'reverse' to change the order to what makes more sense to the user.
I could work on that.

**Comment by gugod** [comment]
0.81 implemented this feature.
