### ISSUE TITLE
perlbrew.pl attempts to load CSS from insecure source

### ISSUE THREAD

**Issue by Grinnz** [gugod/App-perlbrew#579]
I get this error in Chrome:
```
perlbrew.pl/:9 Mixed Content: The page at 'https://perlbrew.pl/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Vollkorn:regular,bold'. This request has been blocked; the content must be served over HTTPS.
```
The CSS appears to work with https so it should work if the protocol is changed in the link.

**Comment by gugod** [comment]
This should be fixed now. The whole site is rebuilt and should not contain the "Mixed Content" js/css link.

Thanks !
