### ISSUE TITLE
Uses wrong make command

### ISSUE THREAD

**Issue by nigelhorne** [gugod/App-perlbrew#600]
Perlbrew has 'make' hardwired, whereas it should use $Config{'make'}.  This would help on Solaris machines, for example, where it's useful to use gmake instead of make.

**Comment by gugod** [comment]
@nigelhorne -- thanks for the information.

I've pushed a commit 62e3c5b49fb77a5524e55d7c34df38f6dcddfed4 for this issue, see if that make sense to you.

However, I'd like to bring up that the documentation about `$Config{make}` does not seem to match your description. Perhaps the documentation requires some updates.

See it here: http://perldoc.perl.org/Config.html#m

make

Quote:

> From Loc.U:
> 
> This variable is used internally by Configure to determine the full pathname (if any) of the make > > program. After Configure runs, the value is reset to a plain make and is not useful.

**Comment by nigelhorne** [comment]
Then perhaps you'd prefer to honour the MAKE environment variable?  However you achieve it, please use gmake on Solaris, not make.

**Comment by gugod** [comment]
@nigelhorne that's an excellent suggestion. It will be done. 👍
