### ISSUE TITLE
It is impossible to pass -A flags when building blead

### ISSUE THREAD

**Issue by ribasushi** [gugod/App-perlbrew#606]
The [version comparison function](https://github.com/gugod/App-perlbrew/blob/release-0.82/lib/App/perlbrew.pm#L730-L754) has no smarts to recognize what `blead` and `perl-blead` mean. As a result [this ( likely harmless )](https://github.com/gugod/App-perlbrew/blob/release-0.82/lib/App/perlbrew.pm#L1728-L1729) and more importantly this [**option destroying** codepath](https://github.com/gugod/App-perlbrew/blob/release-0.82/lib/App/perlbrew.pm#L1695-L1698) are activated when one attempts `perlbrew --as blead_$(date +%F) install -A"...somestuffhere..." blead`

**Comment by fluca1978** [comment]
Good point!
I'm not really sure the new implementation I proposed fixes the issue, any comment is appreciated.

**Comment by ribasushi** [comment]
It seems like this has been properly fixed now, closing
