### ISSUE TITLE
Link parsing broken by href being absolute

### ISSUE THREAD

**Issue by CandyAngel** [gugod/App-perlbrew#617]
Listing of available perls is broken as the href attribute is now absolute, rather than relative.

https://github.com/gugod/App-perlbrew/blob/d3c1df080f42abdbb63c9fc851a7243b488ac0b8/lib/App/perlbrew.pm#L873

This prevents `perlbrew available` from working, and might also be breaking `perlbrew install stable`.

**Comment by gugod** [comment]
Thanks for the suggestion. So far the links in the source code of `https://www.cpan.org/src/5.0/` are still relative links at the moment, but we should still make some change so it will works for both relative and absolute links.

**Comment by gugod** [comment]
If you were referring to the fact that `perlbrew available` shows nothing but cperl, it is fixed by @jmaslak  with commit 0983d7abacbe17180b58e4a37b2332fec86affac 
👍

**Comment by gugod** [comment]
fixed in 0.84
