### ISSUE TITLE
bin/perlbrew doesn't get installed

### ISSUE THREAD

**Issue by gregoa** [gugod/App-perlbrew#619]
Module::Build::Tiny expects executables in script/ (and ignores bin/), so bin/perlbrew doesn't get installed.

**Comment by gugod** [comment]
Fixed in 0.84 .

**Comment by gregoa** [comment]
On Sat, 23 Jun 2018 21:56:15 -0700, Kang-min Liu wrote:

> Fixed in 0.84 .

Thanks for the quick fix!

Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-
