### ISSUE TITLE
install perl failure on AIX 7.1

### ISSUE THREAD

**Issue by ehingsbe** [gugod/App-perlbrew#625]
I'm using a new installation of perlbrew 0.84 on AIX 7.1, attempting to install Perl ("perlbrew install perl-5.28.0") on a new host that has only the system Perl.
It fails each time, with the following text in the log:
>     Auto-guessed '5.28.0'    
>     patching Configure
>     Can't open file Configure
>     Assertion failed: hunk, file  patch.c, line 375
>     Died at /usr/gentran/common/perl5/bin/patchperl line 538.
>     ##### Brew Failed #####

I noticed that the permissions on Configure did not include write, so I did chmod 750 Configure, and I attempted to manually run the patch, and got:
```
# /bin/patch  -p0 <tmp.diff
Hmm...  Looks like a copied context diff to me...
The text leading up to this was:
--------------------------
|diff --git a/Configure b/Configure
|index e12c8bb..1a8088f 100755
|--- Configure
|+++ Configure
--------------------------
Patching file Configure using Plan A...
Assertion failed: hunk, file  patch.c, line 375
IOT/Abort trap (core dumped)
```
 
The contents of the tmp.diff file:
> diff --git a/Configure b/Configure
> index e12c8bb..1a8088f 100755
> --- Configure
> +++ Configure
> @@ -25151,6 +25151,8 @@ zcat='$zcat'
>  zip='$zip'
>  EOT
> 
>  
> +echo "BuiltWithPatchPerl='1.52'" >>config.sh
> +
>  : add special variables
>  $test -f $src/patchlevel.h && 
>  awk '/^#define[        ]+PERL_/ {printf "%s=%s\n",$2,$3}' $src/patchlevel.h >>config.sh
> 

What can I do to additionally troubleshoot this problem?

Additionally (of near insignificance), "perlbrew install stable" reports: "ERROR: Unable to retrieve the list of perls."

**Comment by erickpaquin** [comment]
@ehingsbe , Is this issue still relevant? If not, time to close it? Thanks.

**Comment by ehingsbe** [comment]
Please close.
I don't recall what took place, but now I'm running 5.28.3 successfully.
Thank you!

**Comment by Chi-Iroh** [comment]
In case anyone finds this issue, I just had something the same problem on IBM i (not AIX, but close) with another project.
https://gitlab.gnome.org/GNOME/glib/-/work_items/4058

It turned out I only had an old pre-installed incomplete `patch` command, which doesn't seem to support complex diffs (with commit messages). Installing GNU patch with `yum install patch-gnu` fixed the problem for me, that new command behaved correctly.

Perhaps it's the same thing to do on AIX.
