### ISSUE TITLE
perlbrew switch on WSL opens subshell

### ISSUE THREAD

**Issue by srchulo** [gugod/App-perlbrew#649]
When I try perlbrew switch, I get this response:

`A sub-shell is launched with perl-5.28.0 as the activated perl. Run 'exit' to finish it.`

But my perl when I exit the sub-shell is is still the system perl. I'm running Ubuntu on Windows Subsystem for Linux, I also don't know if it's relevant, but shell is zsh, and I've been unable to install any perls successfully without cd-ing into the directory and running `make install`. Even using --force didn't work, and just gave the same error message suggesting that I use force. Here's my failed build log, in case it helps:

https://gist.github.com/srchulo/4f3cde23fcea3f69d9cde987fb4764b8

**Comment by hurricup** [comment]
Isn't this how perlbrew works? When you switch, it opens subshell with desired perl. After you exiting subshell, you are back to the perl you has by default. 
About wsl - using myself. However, can't remember if I've installed them with tests suppressed. WSL is still imperfect and some things may just not work. Still unsure if it was like this.

**Comment by srchulo** [comment]
Oh, I see. So you're saying that this line in my .bashrc:

` source ~/perl5/perlbrew/etc/bashrc`

Opens a subshell? I guess that makes sense. So it seems like my problem then might be that there is know support for the zsh shell?

And yeah, the WSL thing I assume would be a separate bug, and may be WSL's fault. I thought I'd mention it in case it was relevant, but it sounds like it's not. After installing though, perl seems to be running fine even though it didn't pass the tests.

**Comment by hurricup** [comment]
I was talking about interactive switch. Sourcing just configuring a top level shell and do some other stuff.

**Comment by srchulo** [comment]
Well I'm not sure what you mean by interactive switch. I thought `perlbrew switch` was a permanent switch, and I though `perlbrew use` was only for the current shell.

**Comment by hurricup** [comment]
I ment by interactive - swtitching from console. But you are right and i was wrong.
I've checked by ubuntu wsl. I have a perlbrew installed from apt
`perlbrew/bionic,now 0.82-1 all [installed] `
And switch works without opening subshell and keeps selection between sessions.
In my `.bashrc` I have 
```
PATH="/home/hurricup/perl5/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/hurricup/perl5/lib/perl5${PERL5LIB:+:${PERL5LIB}}"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/hurricup/perl5${PERL_LOCAL_LIB_ROOT:+:${PERL_LOCAL_LIB_ROOT}}"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/hurricup/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/hurricup/perl5"; export PERL_MM_OPT;
```
In my `.bash_profile` I have (not sure, probably I've added it myself)
```
source ~/perl5/perlbrew/etc/bashrc
```

**Comment by srchulo** [comment]
Yes, using bash for me seems to work, too (between sessions). I guess I just can't use zsh as my shell for this to work. Maybe I'll just switch to bash when doing perl, but it would be nice for zsh to be supported.

**Comment by hurricup** [comment]
have you tried to add configs to zsh-related configs? I'm not familiar with it, but may be it works as it is?

**Comment by hurricup** [comment]
Unfortunately, I'm not familiar with zsh and can't help here. However, you could take a peek to https://github.com/rvm/rvm which is a `perlbrew` for `ruby`. It supports `zsh` and probably could help you. And probably, you could contribute here :)

**Comment by gugod** [comment]
@srchulo zsh itself can evaluate most of bash statements just fine. Particularly, doing `source ~/perl5/perlbrew/etc/bashrc` in zsh should work.

That said, there mighte be some system-specific matter that might interfer the execution order of zshrc / zprofile. For example, macOS re-order entries inside `$PATH` in `/etc/zprofile` and the version-switching via sub-shell would never work without changing part of `/etc/zprofile`.

Roughly speaking, try to delay the execution of `source ~/perl5/perlbrew/etc/bashrc` in your zsh env to be as late as possible -- preferrably right before you start interact with your zsh session. (Usually that's the end of `~/.zprofile` or `~/.zshrc`.)

**Comment by srchulo** [comment]
Awesome! Including `source ~/perl5/perlbrew/etc/bashrc` as the last line in `~/.zprofile` did the trick (I had to create this file). 

In case it helps anyone else, when I included it in `~/.zshrc`, I got this error:

```
/home/srchulo/perl5/perlbrew/etc/bashrc:57: defining function based on alias `perlbrew'
/home/srchulo/perl5/perlbrew/etc/bashrc:57: parse error near `()'
```

Thanks for the help :)

**Comment by josephzsombor** [comment]
I am a zsh user and I could reproduce the same problem you had by commenting out the following line from my ~/.zshrc:
`source /home/user/perl5/perlbrew/etc/bashrc #perlbrew'`
So it's fine to put the bashrc line in your .zshrc.
