### ISSUE TITLE
Not a CODE reference at /home/travis/perl5/perlbrew/bin/perlbrew line 2615.

### ISSUE THREAD

**Issue by karenetheridge** [gugod/App-perlbrew#652]
Seen in a blead build on travis tonight -- https://api.travis-ci.org/v3/job/468538791/log.txt

**Comment by Pascal666** [comment]
I'm getting the same error on perl-5.29.x.  perl-5.28.x work fine.

**Comment by Pascal666** [comment]
Same error for:
cperl-5.24.4
cperl-5.26.4
cperl-5.28.0
cperl-5.28.1
cperl-5.29.0

**Comment by nigelhorne** [comment]
Same on 5.18.2.

```
This could take a while. You can run the following command on another shell to track the status:

  tail -f ~/perl5/perlbrew/build.perl-5.18.2.log

Not a CODE reference at /home/smoker/perl5/perlbrew/bin/perlbrew line 2615.
```

**Comment by Pascal666** [comment]
@nigelhorne 
```
# perlbrew install -n perl-5.18.2
Installing /root/perl5/perlbrew/build/perl-5.18.2/perl-5.18.2 into ~/perl5/perlbrew/perls/perl-5.18.2

This could take a while. You can run the following command on another shell to track the status:

  tail -f ~/perl5/perlbrew/build.perl-5.18.2.log

perl-5.18.2 is successfully installed.
# perlbrew --version
/root/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.85
# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

**Comment by nigelhorne** [comment]
@Pascal666 

```
$ cat /etc/debian_version 
buster/sid
```

**Comment by mabman123** [comment]
Can confirm this error with perlbrew 0.85 on Debian Buster (system Perl is 5.28.1), no matter what version of perl or cperl installation is tried via perlbrew.

I was able to install perlbrew 0.84 on the same system via "cpan GUGOD/App-perlbrew-0.84.tar.gz" (I deleted my ~/perl5 directory first as it was a fresh install and I had nothing important there - that may not be necessary).  Perlbrew 0.84 worked as expected for me when installing perl-5.29.6 - no errors.

**Comment by trizen** [comment]
I can also confirm this issue. There seems to be a typo at [line 2363](https://github.com/gugod/App-perlbrew/blob/b84aa406b50856b47653bdb2a87c4fa1f6c4e7cb/lib/App/perlbrew.pm#L2363):


```perl
$executable->symlink ($root->perls ($perl)->bin->($name));
```

needs to be changed to:

```perl
$executable->symlink ($root->perls ($perl)->bin($name));
```

**Comment by Hoembi** [comment]
Hi, ran into the same problem and was wondering if someone could help me with circumventing this problem and tell me how I can install the 0.84 version of perlbrew (don't have CPAN on the cluster so cannot use what mabman123 used).

**Comment by brotbert** [comment]
Is there any date for a fix in the release?

**Comment by Pascal666** [comment]
Confirmed fixed.  Thank you!
