### ISSUE TITLE
Verbose still passes quiet to wget and silent to curl

### ISSUE THREAD

**Issue by Pascal666** [gugod/App-perlbrew#653]
Perlbrew will hang or crash if curl or wget have a problem, but no progress or error messages will be displayed, even with the verbose option, because silent/quiet are always passed to curl/wget.

I wrote the below to fix this problem, but I can't figure out where to insert it.

      if ($self->{verbose}) {
          for my $c (keys %commands) {
              for my $k (keys $commands{$c}) {
                  $commands{$c}{$k} =~ s/silent|quiet/verbose/;
              }
          }
      }

**Comment by gugod** [comment]
Implemented in PR #740
