### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by nigelhorne** [gugod/App-perlbrew#655]
I can't work out why I'm seeing this:

`Not a CODE reference at /home/smoker/perl5/perlbrew/bin/perlbrew line 2615.`

Clearly I'm doing something wrong, but maybe perlbrew isn't validating data properly and as a result it's not telling me what.

**Comment by nigelhorne** [comment]
If it helps, what I've recently done is changed my script to use the -Accflags option to install.

**Comment by Pascal666** [comment]
Duplicate of #652
