### ISSUE TITLE
Failed to connect to raw.githubusercontent.com port 443: Connection refused

### ISSUE THREAD

**Issue by freedog8** [gugod/App-perlbrew#661]
what is raw.githubusercontent.com, I just stuck at here~~
![image](https://user-images.githubusercontent.com/21093659/51360687-a8aad600-1b07-11e9-95a8-0f9374a1b177.png)

**Comment by gugod** [comment]
@freedog8 does it require proxy in your network to access external websites ?

BTW, what perlbrew command leads you to this output ?

**Comment by freedog8** [comment]
Thanks @gugod 
proxy is the mater~
It output this when I try to install perlbrew `curl -L https://install.perlbrew.pl | bash`
The strange thing is that I can install it on another pc within the same network
