### ISSUE TITLE
Perlbrew.pl SSL certificate has expired

### ISSUE THREAD

**Issue by bcantoni** [gugod/App-perlbrew#667]
I notice the Let's Encrypt SSL certificate for https://perlbrew.pl has expired. It looks like it expired earlier today (2019-05-05).

![image](https://user-images.githubusercontent.com/58372/57205828-2939f900-6f76-11e9-96f7-563f7a63a995.png)

**Comment by unixorn** [comment]
This broke a CI check on a PR in https://github.com/unixorn/sysadmin-reading-list

**Comment by gugod** [comment]
Sorry guys. My auto-renewal cronjob was broken by... me-- . :-)

Now they are good!

**Comment by bcantoni** [comment]
> Sorry guys. My auto-renewal cronjob was broken by... me-- . :-)

Confirmed all looks good now! Perlbrew really saved me on an older shared host I needed to fix where I didn't have root access.
