### ISSUE TITLE
Installation of perl 5.14.2 freezes

### ISSUE THREAD

**Issue by MrBeardyDrummer** [gugod/App-perlbrew#672]
Hello,

I am trying to install perl to prove a theory, however when I try the installation freezes at this certain point and I have to kill the install manually. As far as I am aware, my perlbrew is completely up to date as I only installed it today. 

op/magic-27839.t .................................................. ok
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
##### Brew Failed #####

I'm trying to install on Ubuntu 16.04 with a  current perl version of v5.22.1

This is currently blocking me on a fairly important project, any assistance would be greatly appreciated!! If you need any more info please let me know.

**Comment by gugod** [comment]
@MrBeardyDrummer were you able to get any help after all ? This is unlikely an issue of perlbrew itself, but how it interact with env/perl/patchperl.

Anyway, I'd like to close this issue due to the lack of discussion. Feel free to re-open it if necessary.
