### ISSUE TITLE
Building against blead may be broken soon

### ISSUE THREAD

**Issue by toddr** [gugod/App-perlbrew#677]
perl5.git.perl.org is going to be shut down soon. The primary repo for perl is now located on github as https://github.com/Perl/perl5 . A blead tarball can now be retrieved from blead but needs to come from this URL. https://github.com/Perl/perl5/tarball/blead Thanks to @haarg, we can provide the commit SHA via https://github.com/Perl/perl5/pull/17199 . perlbrew needs to be updated to use this instead. 

I'm opening this ticket to track the needed change.

**Comment by haarg** [comment]
Related: tokuhirom/Perl-Build#95

**Comment by gugod** [comment]
A tentative commit 8d64420 is pushed to the develop branch which can process the new blead archive downloaded from github. Feel free to help testing by checking out the develop branch and see if `perl -Ilib ./script/perlbrew install blead` can finish what it is supposed to do.

**Comment by toddr** [comment]
Blead now includes https://github.com/Perl/perl5/pull/17199 so a fix for this should be able to proceed.

**Comment by toddr** [comment]
Are we just waiting on a release for this?

**Comment by toddr** [comment]
https://github.com/Perl/perl5/projects/1#card-28052040

**Comment by gugod** [comment]
@toddr

I forgot to update the status of issue. perlbrew 0.87 was released. The URL of blead tarball is now: https://github.com/Perl/perl5/archive/blead.tar.gz

I guess that means we can close this ticket. (Feel free to re-open it when necessary)
