### ISSUE TITLE
cperl not listed with `perlbrew list`

### ISSUE THREAD

**Issue by tobyink** [gugod/App-perlbrew#688]
Also cannot be switched to with `perlbrew use` or `perlbrew switch`.

This is because the standard `make install` for cperl doesn't create a binary called `perl` but a binary called `cperl` instead.

If you do this, everything works okay:

```
perlbrew install --notest cperl-5.30.0
ln -s $PERLBREW_ROOT/perls/cperl-5.30.0/bin/{cperl,perl}
```

But it would be nice if the linking didn't need to be done manually.

**Comment by gugod** [comment]
@tobyink may I ask what version of perlbrew are you using ? I just verified that this seems to be working at 0.88 and perhaps a few earlier version too.

I'll try this on a linux just to be sure that it's not platform-specific.

**Comment by tobyink** [comment]
@gugod 0.88 currently but I could have been using an older version when I filed the issue. I'll try installing cperl now.

**Comment by tobyink** [comment]
Hmm, it worked! Now I guess it's time to see if I can do it on Travis.
