### ISSUE TITLE
perlbrew no longer installs on macOS BigSur

### ISSUE THREAD

**Issue by vanHoesel** [gugod/App-perlbrew#701]
I got this interesting output from `perlbrew install ...`
```Which of these apply, if any? [darwin]

*** Unexpected product version 11.0.
***
*** Try running sw_vers and see what its ProductVersion says.

##### Brew Failed #####
```
soo...
```
> sw_vers
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

**Comment by vanHoesel** [comment]
Long ago, when I got my first Macintosh IIfx, it had MacOS 7.6.
Time goes by, and we go all the way up to MacOS 9.2.
Then Apple makes a huge change and started to use 'UNI**X**' like systems and the OS changed to MacOS-X, also know as MacOS 10
Then we two decades of big cats and national monuments, all fancy names for 'minor updates' from MacOS 10.0 to 10.14.

Then we had 'Big Sur', and silently it stopped being MacOS 10.

Welcome to MacOS 11.0

**Comment by gugod** [comment]
@vanHoesel Related thread in perl5 repo : https://github.com/Perl/perl5/pull/17946

**Comment by vanHoesel** [comment]
After a `patch-perl` things were better.

But still end up with a irritating error, that I may have to forward to Perl instead:
```
ext/DynaLoader/t/DynaLoader ...
Failed test 20 - array should contain one result or more: libc => () at t/DynaLoader.t line 127
#      got "0"
# expected >= "1"
FAILED at test 20

...

Failed 1 test out of 2448, 99.96% okay.
	../ext/DynaLoader/t/DynaLoader.t
### Since not all tests were successful, you may want to run some of
### them individually and examine any diagnostic messages they produce.
### See the INSTALL document's section on "make test".
### You have a good chance to get more information by running
###   ./perl harness
### in the 't' directory since most (>=80%) of the tests succeeded.
### You may have to set your dynamic library search path,
### DYLD_LIBRARY_PATH, to point to the build directory:
###   setenv DYLD_LIBRARY_PATH `pwd`; cd t; ./perl harness
###   DYLD_LIBRARY_PATH=`pwd`; export DYLD_LIBRARY_PATH; cd t; ./perl harness
###   export DYLD_LIBRARY_PATH=`pwd`; cd t; ./perl harness
### for csh-style shells, like tcsh; or for traditional/modern
### Bourne-style shells, like bash, ksh, and zsh, respectively.
```
for `perl-blead`

**Comment by Leont** [comment]
> But still end up with a irritating error, that I may have to forward to Perl instead:

That looks like Perl-Toolchain-Gang/ExtUtils-MakeMaker#381

**Comment by vanHoesel** [comment]
I trust that the people involved come up with a very good solution

**Comment by Leont** [comment]
This should be resolved with the latest version of Devel::PatchPerl

**Comment by gugod** [comment]
https://github.com/gugod/patchperl-packing/commit/08beae5321d5b2bbf94629c04cea025b8354abf9

Looks like the minion finished building the fatpacked `patchperl` -- if we rerun `perlbrew install-patchperl`, that shoud be installed and the building problem should be resolved.  :)

**Comment by gugod** [comment]
Although I ran into issuse when compiling some legacy versions,  recent versions are all compilable. 

I'm closinsg this issue. Thanks everyone who participated.
