### ISSUE TITLE
Failed in installing Perl to version 5.32.0 with Perlbrew under macOS Big Sur

### ISSUE THREAD

**Issue by besthq** [gugod/App-perlbrew#703]
The current version of Perl on my macOS Big Sur is **perl-5.28-2 built for Darwin-thread-multi-2level**

I would like to update the Perl version to **5.32.0** with Perlbrew tool, however, it fails.
The last messages recorded in the log are:

-----
../lib/warnings.t .................................................. ok

Test Summary Report
../ext/DynaLoader/t/DynaLoader.t (Wstat: 0 Tests: 44 Failed: 1)
Failed test: 20
Files=2678, Tests=1208546, 764 wallclock secs (56.28 usr 10.21 sys + 419.08 cusr 53.08 csys = 538.65 CPU)
Result: FAIL
make: *** [test_harness] Error 1

Brew Failed

-----

**Comment by gugod** [comment]
Duplicate #701
