### ISSUE TITLE
perlbrew vs plenv

### ISSUE THREAD

**Issue by hongyi-zhao** [gugod/App-perlbrew#704]
Some comparisons have been given [Here](https://github.com/tokuhirom/plenv#plenv-vs-perlbrew) by the author of plenv. But I also want to know the points of view from developers of perlbrew.

Any hints/notes/comments are highly appreciated.

Regards,
HY

**Comment by gugod** [comment]
Not sure what types of content  are you looking for, but I did gave a short representation about "perlbrew tips and tricks" a while ago: https://www.youtube.com/watch?v=8t9L3qvtKQ8

**Comment by hongyi-zhao** [comment]
I'm familiar with pyenv, so I want to know whether or not perlbrew has less working mechanisms similar to pyenv that plenv.

**Comment by gugod** [comment]
> I'm familiar with pyenv, so I want to know whether or not perlbrew has less working mechanisms similar to pyenv than that of plenv.

In that perspective, perlbrew depends on many shell helper functions instead of shims when it comes to switching to different version.

**Comment by hongyi-zhao** [comment]
What I care about is the final user experience. Say, for me, if the command line options/operations and perl venv folders' layouts are  similar to those for pyenv, then I will be able to quickly adapt to this tool and use it in a production environment.

**Comment by gugod** [comment]
If you are williing to share the pros/cons of these tools here, please allow me to repost it on https://perlbrew.pl website (which is backed by the Wiki of this project)

**Comment by hongyi-zhao** [comment]
I'm only familiar with pyenv by now. As far as perlbrew and plenv are concerned,  I havn't experience at all.

**Comment by gugod** [comment]
FYI I opened up the Discussion tab: https://github.com/gugod/App-perlbrew/discussions

perhaps in the future we should use that for conversations instead of using "Issues" 

meanwhile this issues is closed since there are no obvious follow-up actions.
