### ISSUE TITLE
 sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" is broken 

### ISSUE THREAD

**Issue by Karram-Ayman** [gugod/App-perlbrew#719]
sh: -c: line 0: syntax error near unexpected token `newline'
sh: -c: line 0: `<!DOCTYPE html>'

**Comment by erickpaquin** [comment]
@Karram-Ayman . Why is this issue raised in "App-perlbrew" ? Isn't this something related to Robby Russel's "oh-my-zsh" ? Shouldn't it be opened there instead? Can this one be closed?
