### ISSUE TITLE
clone-modules: progress message has it backwards

### ISSUE THREAD

**Issue by jkeenan** [gugod/App-perlbrew#721]
The "progress message" for `perldoc clone-modules` appears to have things backwards.  Today I went to use it to clone modules from 5.32 to 5.34.  So I said:
```
$ perlbrew clone-modules 5.32.0 5.34.0
```
... and immediately the output was this:
```
Installing 104 modules from 5.34.0 to 5.32.0 ...
--> Working on App::perlbrew
Fetching http://www.cpan.org/authors/id/G/GU/GUGOD/App-perlbrew-0.92.tar.gz ... OK
Configuring App-perlbrew-0.92 ... OK
...
```
Shouldn't it have been this?
```
Installing 104 modules from 5.32.0 to 5.34.0 ...
```

**Comment by gugod** [comment]
That looks like some old behaviour -- iirct it was indeed showing those two names in the opposite order, but at least with the latest version (0.92), or perhaps a few version earlier, the order is correct.

**Comment by jkeenan** [comment]
> That looks like some old behaviour -- iirct it was indeed showing those two names in the opposite order, but at least with the latest version (0.92), or perhaps a few version earlier, the order is correct.

Thanks.   I had had no reason to upgrade for a long time but did so now.
```
$ perlbrew --version
/home/jkeenan/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.84
$ perlbrew self-upgrade
perlbrew is installed: ~/perl5/perlbrew/bin/perlbrew

perlbrew root (~/perl5/perlbrew) is initialized.
$ perlbrew --version
/home/jkeenan/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.92
```
