### ISSUE TITLE
perlbrew.pl says latest stable release is 5.16.0, please update to 5.34.0

### ISSUE THREAD

**Issue by hakonhagland** [gugod/App-perlbrew#726]
From the [web page](https://perlbrew.pl/) :   

![perlbrew](https://user-images.githubusercontent.com/6708379/121588730-90201b00-ca36-11eb-875f-d1a5fe87a954.png)

The page sort of "indicates" that 5.16.0 is the latest stable release, whereas it is actually 5.34.0. I think this can be confusing or misleading to newcomers.

**Comment by gugod** [comment]
Thanks ! (looks like this should be an regular task)

It is updated.

Commit: https://github.com/gugod/App-perlbrew/wiki/index/_compare/b98c2d1b0b534728187bb47f32fd34f0e48a1c77...6de121aba7dac0565e4141ec471946fbfa25c64b
