### ISSUE TITLE
Can I introduce my own perl to perlbrew

### ISSUE THREAD

**Issue by janlimpens** [gugod/App-perlbrew#732]
I would want to use my own build in the same way as pre-configured Perls. Is that possible?

**Comment by gugod** [comment]
@janlimpens In a way yes...

perlbrew should be able to recognize installations under `~/perl5/perlbrew/perls`, and make them the target of commands such as: `list`, `use`, `switch`.

If you build perl from source code specify the `prefix` to to a dir inside which, such as:

    ./Configure -Dprefix=~/perl5/perlbrew/perls/perl-my-own-build 

... then, afte full installation process, you should be able to refer to it as `perl-my-own-build` in perlbrew commands.

You could give a quick try by unzipping the binary release of [relocatable-perl](https://github.com/skaji/relocatable-perl) there. The name of the target folder becomes the "installation name" in perlbrew.

**Comment by gugod** [comment]
FYI I've setup the "Discussion" for this project -- feel free to use it for general discussions -- https://github.com/gugod/App-perlbrew/discussions

Meanwhile I think my answer about should be enough (perhaps deserver a wiki page too) and therefore I'm closing this issues.
