### ISSUE TITLE
Stray ./Build in tarball

### ISSUE THREAD

**Issue by gregoa** [gugod/App-perlbrew#733]
The 0.93 tarball on CPAN contains a `Build` file which makes building the distribution (at least in the context of a Debian package) a bit cumbersome, as (the clean stage is invoked first and) we don't have `#!/Users/gugod/perl5/perlbrew/perls/perl-5.8.9/bin/perl` available :)

Please check in the next release that it's removed.

Cheers,
gregor, Debian Perl Group

**Comment by gugod** [comment]
@gregoa ouch, my bad.

evidently I need to do a git clean -xdf before making new releases.


I am not sure when that will be though, since there are no mew changes yet. However, since that mistske probably impact e build of other types sf packages, I don't mind making a new one just for patching this mistake.

**Comment by gregoa** [comment]
(Or a ./Build {real,dist,something}-clean maybe.)

For the Debian package I worked around the file, but yeah, it might affect others, so another release might be a good idea.

Thanks,
gregor

**Comment by gugod** [comment]
I've  uplodade new release (version 0.94) with one small change. This time `Build` is properly removed.

Thanks @gregoa for reporting this. 👍

**Comment by gregoa** [comment]
On Sat, 04 Dec 2021 16:02:19 -0800, Kang-min Liu wrote:

> I've  uplodade new release (version 0.94) with one small change. This time `Build` is properly removed.
> Thanks @gregoa for reporting this. 👍 

Thanks!
0.94 uploaded to Debian/unstable.

Cheers,
gregor 

-- 
 .''`.  https://info.comodo.priv.at -- Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member VIBE!AT & SPI Inc. -- Supporter Free Software Foundation Europe
   `-   NP: Leonard Cohen: Bird on a Wire
