### ISSUE TITLE
Version # mismatch

### ISSUE THREAD

**Issue by ronsavage** [gugod/App-perlbrew#734]
ron@zigzag:~$ cpanm App::perlbrew
App::perlbrew is up to date. (0.93)
ron@zigzag:~$ perlbrew version
/home/ron/perl5/perlbrew/bin/perlbrew  - App::perlbrew/0.92

**Comment by ronsavage** [comment]
Agghh. Ignore the strikeouts. The text itself is exactly what I posted. Thanx

**Comment by gugod** [comment]
@ronsavage I think your `/home/ron/perl5/perlbrew/bin/perlbrew` is something installed not by doing `cpanm` but by doing:

    curl -L https://install.perlbrew.pl | bash

To upgrade that one, do this:

    perlbrew self-upgrade

**Comment by ronsavage** [comment]
Hi Kang-min

You are correct. And the self-upgrade worked, of course.

$many x $thanx;

---
Cheers
Ron
savage.net.au
