### ISSUE TITLE
Site install.perlbrew.pl is not responding

### ISSUE THREAD

**Issue by idnorton** [gugod/App-perlbrew#756]
Hi,

The install site https://install.perlbrew.pl/ is not responding to http or https requests. Not sure where to raise this issue, but here seemed like a good start.

Thanks!

**Comment by Nowaker** [comment]
You can use this instead:
```
RUN curl -kL https://raw.githubusercontent.com/gugod/App-perlbrew/develop/perlbrew-install | bash
```

@gugod I'd like to use this approach permanently, but I'd like to be able to use the latest release and not master. Would it be possible to always tag the latest release as simply `release`, in addition to `release-[version]`?

**Comment by gugod** [comment]
@Nowaker , @idnorton 

Hi,

The two instruction suggested by @Nowaker will work when `perlbrew.pl` website is down (it's rebooted and back BTW. Thanks for letting me know!), but they would both install the latest release and not different versions as it seams (Perhaps it'll be nice if they do). Both of those two command downloads the same installer, an the intsaller would fetch the latest relelease of `perlbrew` execuatble from:

    https://raw.githubusercontent.com/gugod/App-perlbrew/master/perlbrew

To insall a specific version of perlbrew, at the moment, the only way is to set `PERLBREWURL` before running installer. Something like this should take the `perlbrew-installer` from master branch, then install the `perlbrew` from release-0.96.

```bash
export PERLBREWURL=https://raw.githubusercontent.com/gugod/App-perlbrew/release-0.96/perlbrew
curl -L https://raw.githubusercontent.com/gugod/App-perlbrew/master/perlbrew-install | bash
```

> but I'd like to be able to use the latest release and not master

Conventionally  the HEAD of `master` branch is always the same as the latest release. The `master` branch in this repo is only updated when there is a new release.  The `release-vN.NN` tags should always be made on the master branch (if I'm not making stupid mistakes :-)

**Comment by Nowaker** [comment]
@gugod You totally misunderstood my suggestion. Please reread ;)

**Comment by Nowaker** [comment]
@gugod I didn't spot you have a Git Flow like repo. It's fine then. Thank you.

**Comment by gugod** [comment]
@Nowaker Yes I've been using Git Flow in this repo. It is a bit overkill since this is mostly a 1-person project so there are many cases that I did'nt quite follow... but I do intend to keep the HEAD of `master` to be always the same as latest release. :-)

**Comment by gugod** [comment]
I don't think there is anything more to be done for this issue. It'll be closed.
