### ISSUE TITLE
Cannot import modules with `cpm`: `install-cpm` vs `install-cpanm` commands

### ISSUE THREAD

**Issue by rwp0** [gugod/App-perlbrew#797]
I can install and **use** modules after doing `install-cpanm`:

```
perlbrew install-cpanm

cpanm Path::Tiny

perl -M Path::Tiny
```

But I cannot `use` (import) modules after doing `install-cpm` successfully:

```
perlbrew install-cpanm

cpm install URI

perl -M URI

# Can't locate URI.pm in @INC
```

I'd prefer `cpm` to `cpanm` because of its non-verbosity and colors, but *what* am I doing wrong?

Do I need to do additional configuration manually after issuing the `install-cpanm` command for the `cpm` utility to install modules to usual paths or be the same as `cpanm`?

Not very familiar with it, and thinking perhaps I need to do some tweaks for `cpm` for the brewed `perl` to recognize the modules (if that's not done by default by `perlbrew` after doing `install-cpm` ).

Thanks

**Comment by rwp0** [comment]
Seems like we need to use the `-g` option of the `install` command as documented in the [SYNOPSIS](https://metacpan.org/dist/App-cpm/view/script/cpm#SYNOPSIS)(accessible with `cpm --help`)

```
# install module into current @INC instead of local/
> cpm install -g Module
```

**Comment by smonff** [comment]
You could also indicate the `local` directory explicitly: 

    perl -Ilocal -MURI

@rwp0

**Comment by rwp0** [comment]
Thanks @smonff good to know.

It seems to me that `cpm` differs from `cpan` and `cpanm` by always using `local::lib` and thereby installing to `local` by default.

**Comment by rwp0** [comment]
> It helps to keep each projects dependencies isolated, like npm and node_modules in the Nodejs world.

I don't understand this part.
How installing the modules in a central `~/local` directory keeps them isolated per project (since each project is having its own directory)?

**Comment by smonff** [comment]
If you don't use the `-g` flag, it install dependencies to the current location.

**Comment by rwp0** [comment]
> If you don't use the `-g` flag, it install dependencies to the current location.

Oh yeah now I understand it

```
mkdir project
cd project
cpm install Path::Tiny
less ./local/lib/perl5/Path/Tiny.pm
```

Like `npm` does.

Thanks a lot! 🙂
