### ISSUE TITLE
Deletes PERL5LIB right before patchperl fails to find Devel::PatchPerl

### ISSUE THREAD

**Issue by chadadavis** [gugod/App-perlbrew#97]
Saw the announcement about Ubuntu 11.04 and upgraded Perlbrew to 0.21 and Devel::PatchPerl to 0.36, but I still can't install perl-5.12.3 because patchperl fails to find Devel::PatchPerl in PERL5LIB, because Perlbrew.pm deletes it right before it calls patchperl (in do_install_this()). 

My modules are in a local::lib and that's the only way I can install D::PatchPerl on some machines. Not sure how to work around this. I assume PB wants to avoid pollution from PERL5LIB, but how else am I supposed to find D::PatchPerl?

**Comment by gugod** [comment]
I'm just closing this old ticket. Since perlbrew distribution now also incooperate a way to install standalone patchperl executable.
